// lib/watchtower/data-ticker.ts
// Ticker text — loaded only by the prices ticker component.

export const TICKER_TEXT =
  "☢ DOOMSDAY CLOCK: 85 SECONDS — ALL-TIME RECORD — NO NUCLEAR ARMS CONTROL TREATY IN FORCE — BAS JAN 27 2026 · " +
  "⚠ NUCLEAR: CRITICAL 93/100 · CYBER: CRITICAL 85/100 · CIVIL: HIGH 78/100 · ECONOMIC: HIGH 76/100 · BIO: HIGH 74/100 · CLIMATE: ELEVATED 69/100 · " +
  "SALT TYPHOON: 9+ US TELECOMS BREACHED — FBI: ONGOING · IRAN: 3 WEEKS FROM WEAPONS-GRADE URANIUM (IAEA) · SUDAN: WORLD'S LARGEST DISPLACEMENT CRISIS — 14M+ DISPLACED · " +
  "US DEBT $38.43T · 10% UNIVERSAL TARIFF + 145% CHINA — LARGEST US TAX INCREASE SINCE 1993 · H5N1: OUT OF CONTROL IN ANIMAL RESERVOIRS · 2024 HOTTEST YEAR EVER: +1.55°C · ";
