// lib/watchtower/geo-risk-summary.ts
// Globe polygon coloring data — iso/name/level/score/domain/trend/lat/lon only.
// No incidents. ~22 KB vs the 87 KB full geo-risk.ts.
// Loaded eagerly; geo-risk-details.ts is lazy-loaded on country card open.

export type RiskLevel = "CRITICAL" | "HIGH" | "ELEVATED" | "MODERATE";
export type TrendDir  = "↑" | "→" | "↓";

export interface CountryRiskSummary {
  iso:    string;
  name:   string;
  level:  RiskLevel;
  score:  number;
  domain: string;
  trend:  TrendDir;
  lat:    number;
  lon:    number;
}

export const RISK_COLORS: Record<RiskLevel, { fill: string; hover: string; glow: string }> = {
  CRITICAL: { fill: "#b02020", hover: "#e84040", glow: "rgba(232,64,64,0.6)"   },
  HIGH:     { fill: "#a06010", hover: "#f0a500", glow: "rgba(240,165,0,0.5)"   },
  ELEVATED: { fill: "#1a5a7a", hover: "#38bdf8", glow: "rgba(56,189,248,0.4)"  },
  MODERATE: { fill: "#0e4a30", hover: "#1ae8a0", glow: "rgba(26,232,160,0.3)"  },
};

export const NO_DATA_FILL  = "#141e2b";
export const BORDER_COLOR  = "#0a1520";
export const SEA_COLOR     = "#060f1e";

export const COUNTRY_RISK: CountryRiskSummary[] = [
  { iso:"275", name:"Palestine / Gaza", level:"CRITICAL", score:99, domain:"Civil / Political", trend:"↑", lat:31.9, lon:35.2 },
  { iso:"804", name:"Ukraine", level:"CRITICAL", score:97, domain:"Civil / Political", trend:"→", lat:49.0, lon:31.5 },
  { iso:"729", name:"Sudan", level:"CRITICAL", score:95, domain:"Civil / Political", trend:"↑", lat:12.8, lon:30.2 },
  { iso:"408", name:"North Korea", level:"CRITICAL", score:94, domain:"Nuclear / EMP", trend:"↑", lat:40.0, lon:127.0 },
  { iso:"887", name:"Yemen", level:"CRITICAL", score:93, domain:"Civil / Political", trend:"↑", lat:15.5, lon:48.5 },
  { iso:"364", name:"Iran", level:"CRITICAL", score:92, domain:"Nuclear / EMP", trend:"↑", lat:32.0, lon:53.7 },
  { iso:"760", name:"Syria", level:"CRITICAL", score:91, domain:"Civil / Political", trend:"↑", lat:34.8, lon:38.9 },
  { iso:"643", name:"Russia", level:"HIGH", score:89, domain:"Nuclear / EMP", trend:"↑", lat:61.5, lon:90.0 },
  { iso:"156", name:"China", level:"HIGH", score:87, domain:"Civil / Political", trend:"↑", lat:35.0, lon:104.0 },
  { iso:"376", name:"Israel", level:"HIGH", score:85, domain:"Civil / Political", trend:"↑", lat:31.5, lon:34.8 },
  { iso:"104", name:"Myanmar", level:"HIGH", score:84, domain:"Civil / Political", trend:"↑", lat:19.0, lon:96.7 },
  { iso:"004", name:"Afghanistan", level:"HIGH", score:83, domain:"Civil / Political", trend:"→", lat:33.9, lon:67.7 },
  { iso:"180", name:"DR Congo", level:"HIGH", score:82, domain:"Civil / Political", trend:"↑", lat:-4.0, lon:21.8 },
  { iso:"422", name:"Lebanon", level:"HIGH", score:79, domain:"Civil / Political", trend:"→", lat:33.9, lon:35.5 },
  { iso:"706", name:"Somalia", level:"HIGH", score:78, domain:"Civil / Political", trend:"↑", lat:5.0, lon:46.2 },
  { iso:"840", name:"United States", level:"HIGH", score:78, domain:"Cyber / Tech", trend:"↑", lat:39.5, lon:-98.4 },
  { iso:"231", name:"Ethiopia", level:"HIGH", score:77, domain:"Civil / Political", trend:"→", lat:9.0, lon:40.5 },
  { iso:"332", name:"Haiti", level:"HIGH", score:76, domain:"Civil / Political", trend:"↑", lat:18.9, lon:-72.3 },
  { iso:"586", name:"Pakistan", level:"HIGH", score:75, domain:"Nuclear / EMP", trend:"↑", lat:30.4, lon:69.3 },
  { iso:"368", name:"Iraq", level:"HIGH", score:73, domain:"Civil / Political", trend:"→", lat:33.2, lon:43.7 },
  { iso:"434", name:"Libya", level:"HIGH", score:71, domain:"Civil / Political", trend:"→", lat:27.0, lon:18.0 },
  { iso:"716", name:"Zimbabwe", level:"HIGH", score:70, domain:"Economic", trend:"↑", lat:-20.0, lon:30.0 },
  { iso:"112", name:"Belarus", level:"HIGH", score:72, domain:"Civil / Political", trend:"↑", lat:53.7, lon:28.0 },
  { iso:"728", name:"South Sudan", level:"HIGH", score:74, domain:"Civil / Political", trend:"↑", lat:6.9, lon:31.3 },
  { iso:"466", name:"Mali", level:"HIGH", score:75, domain:"Civil / Political", trend:"↑", lat:17.6, lon:-4.0 },
  { iso:"854", name:"Burkina Faso", level:"HIGH", score:76, domain:"Civil / Political", trend:"↑", lat:12.4, lon:-1.6 },
  { iso:"140", name:"Central African Republic", level:"HIGH", score:68, domain:"Civil / Political", trend:"→", lat:6.6, lon:20.9 },
  { iso:"148", name:"Chad", level:"HIGH", score:67, domain:"Civil / Political", trend:"↑", lat:15.5, lon:18.7 },
  { iso:"562", name:"Niger", level:"HIGH", score:69, domain:"Civil / Political", trend:"↑", lat:17.6, lon:8.1 },
  { iso:"356", name:"India", level:"ELEVATED", score:68, domain:"Biological", trend:"↑", lat:20.6, lon:79.0 },
  { iso:"792", name:"Turkey", level:"ELEVATED", score:67, domain:"Economic", trend:"→", lat:39.0, lon:35.2 },
  { iso:"566", name:"Nigeria", level:"ELEVATED", score:66, domain:"Civil / Political", trend:"↑", lat:9.1, lon:8.7 },
  { iso:"818", name:"Egypt", level:"ELEVATED", score:63, domain:"Economic", trend:"↑", lat:26.8, lon:30.8 },
  { iso:"484", name:"Mexico", level:"ELEVATED", score:63, domain:"Civil / Political", trend:"↑", lat:23.6, lon:-102.6 },
  { iso:"862", name:"Venezuela", level:"ELEVATED", score:61, domain:"Economic", trend:"↑", lat:8.0, lon:-66.6 },
  { iso:"682", name:"Saudi Arabia", level:"ELEVATED", score:61, domain:"Economic", trend:"→", lat:23.9, lon:45.1 },
  { iso:"710", name:"South Africa", level:"ELEVATED", score:57, domain:"Economic", trend:"→", lat:-29.0, lon:25.0 },
  { iso:"170", name:"Colombia", level:"ELEVATED", score:55, domain:"Civil / Political", trend:"→", lat:4.1, lon:-72.9 },
  { iso:"076", name:"Brazil", level:"ELEVATED", score:53, domain:"Climate", trend:"→", lat:-10.0, lon:-55.0 },
  { iso:"608", name:"Philippines", level:"ELEVATED", score:57, domain:"Civil / Political", trend:"↑", lat:12.9, lon:121.8 },
  { iso:"360", name:"Indonesia", level:"ELEVATED", score:56, domain:"Climate", trend:"→", lat:-2.5, lon:118.0 },
  { iso:"050", name:"Bangladesh", level:"ELEVATED", score:60, domain:"Civil / Political", trend:"↑", lat:23.7, lon:90.4 },
  { iso:"268", name:"Georgia", level:"ELEVATED", score:55, domain:"Civil / Political", trend:"↑", lat:41.7, lon:44.8 },
  { iso:"051", name:"Armenia", level:"ELEVATED", score:57, domain:"Civil / Political", trend:"→", lat:40.2, lon:44.5 },
  { iso:"031", name:"Azerbaijan", level:"ELEVATED", score:54, domain:"Civil / Political", trend:"→", lat:40.4, lon:47.6 },
  { iso:"498", name:"Moldova", level:"ELEVATED", score:56, domain:"Civil / Political", trend:"↑", lat:47.0, lon:28.9 },
  { iso:"688", name:"Serbia", level:"ELEVATED", score:52, domain:"Civil / Political", trend:"↑", lat:44.0, lon:21.0 },
  { iso:"192", name:"Cuba", level:"ELEVATED", score:58, domain:"Economic", trend:"↑", lat:21.5, lon:-79.5 },
  { iso:"320", name:"Guatemala", level:"ELEVATED", score:54, domain:"Civil / Political", trend:"→", lat:15.8, lon:-90.2 },
  { iso:"340", name:"Honduras", level:"ELEVATED", score:56, domain:"Civil / Political", trend:"↑", lat:14.6, lon:-86.6 },
  { iso:"218", name:"Ecuador", level:"ELEVATED", score:57, domain:"Civil / Political", trend:"↑", lat:-1.8, lon:-78.2 },
  { iso:"604", name:"Peru", level:"ELEVATED", score:53, domain:"Civil / Political", trend:"↑", lat:-9.2, lon:-75.0 },
  { iso:"032", name:"Argentina", level:"ELEVATED", score:52, domain:"Economic", trend:"→", lat:-34.0, lon:-64.0 },
  { iso:"120", name:"Cameroon", level:"ELEVATED", score:55, domain:"Civil / Political", trend:"↑", lat:5.7, lon:12.4 },
  { iso:"800", name:"Uganda", level:"ELEVATED", score:52, domain:"Civil / Political", trend:"↑", lat:1.4, lon:32.3 },
  { iso:"404", name:"Kenya", level:"ELEVATED", score:51, domain:"Civil / Political", trend:"↑", lat:-0.0, lon:37.9 },
  { iso:"508", name:"Mozambique", level:"ELEVATED", score:55, domain:"Civil / Political", trend:"↑", lat:-18.3, lon:35.5 },
  { iso:"324", name:"Guinea", level:"ELEVATED", score:53, domain:"Civil / Political", trend:"↑", lat:11.0, lon:-10.9 },
  { iso:"108", name:"Burundi", level:"ELEVATED", score:54, domain:"Civil / Political", trend:"↑", lat:-3.4, lon:29.9 },
  { iso:"232", name:"Eritrea", level:"ELEVATED", score:56, domain:"Civil / Political", trend:"↑", lat:15.2, lon:39.8 },
  { iso:"762", name:"Tajikistan", level:"ELEVATED", score:51, domain:"Civil / Political", trend:"↑", lat:38.9, lon:71.3 },
  { iso:"598", name:"Papua New Guinea", level:"ELEVATED", score:50, domain:"Civil / Political", trend:"↑", lat:-6.3, lon:143.9 },
  { iso:"144", name:"Sri Lanka", level:"ELEVATED", score:49, domain:"Economic", trend:"↓", lat:7.9, lon:80.7 },
  { iso:"558", name:"Nicaragua", level:"ELEVATED", score:54, domain:"Civil / Political", trend:"↑", lat:12.9, lon:-85.2 },
  { iso:"266", name:"Gabon", level:"ELEVATED", score:48, domain:"Civil / Political", trend:"→", lat:-0.8, lon:11.6 },
  { iso:"070", name:"Bosnia and Herzegovina", level:"ELEVATED", score:50, domain:"Civil / Political", trend:"↑", lat:44.2, lon:17.9 },
  { iso:"462", name:"Maldives", level:"ELEVATED", score:46, domain:"Economic", trend:"↑", lat:3.2, lon:73.2 },
  { iso:"418", name:"Laos", level:"ELEVATED", score:47, domain:"Economic", trend:"↑", lat:17.9, lon:102.6 },
  { iso:"276", name:"Germany", level:"MODERATE", score:42, domain:"Economic", trend:"↑", lat:51.2, lon:10.4 },
  { iso:"392", name:"Japan", level:"MODERATE", score:43, domain:"Nuclear / EMP", trend:"↑", lat:37.0, lon:137.0 },
  { iso:"410", name:"South Korea", level:"MODERATE", score:43, domain:"Civil / Political", trend:"↑", lat:36.5, lon:127.8 },
  { iso:"250", name:"France", level:"MODERATE", score:38, domain:"Civil / Political", trend:"↑", lat:46.2, lon:2.2 },
  { iso:"826", name:"United Kingdom", level:"MODERATE", score:37, domain:"Economic", trend:"→", lat:54.4, lon:-2.2 },
  { iso:"036", name:"Australia", level:"MODERATE", score:31, domain:"Climate", trend:"→", lat:-25.3, lon:133.8 },
  { iso:"124", name:"Canada", level:"MODERATE", score:30, domain:"Economic", trend:"↑", lat:56.1, lon:-106.4 },
  { iso:"380", name:"Italy", level:"MODERATE", score:36, domain:"Economic", trend:"→", lat:42.8, lon:12.8 },
  { iso:"724", name:"Spain", level:"MODERATE", score:34, domain:"Civil / Political", trend:"→", lat:40.4, lon:-3.7 },
  { iso:"616", name:"Poland", level:"MODERATE", score:33, domain:"Civil / Political", trend:"→", lat:51.9, lon:19.1 },
  { iso:"642", name:"Romania", level:"MODERATE", score:32, domain:"Civil / Political", trend:"↑", lat:45.9, lon:24.9 },
  { iso:"233", name:"Estonia", level:"MODERATE", score:35, domain:"Cyber / Tech", trend:"↑", lat:58.6, lon:25.0 },
  { iso:"428", name:"Latvia", level:"MODERATE", score:34, domain:"Cyber / Tech", trend:"↑", lat:56.9, lon:24.6 },
  { iso:"440", name:"Lithuania", level:"MODERATE", score:34, domain:"Civil / Political", trend:"↑", lat:55.2, lon:23.9 },
  { iso:"348", name:"Hungary", level:"MODERATE", score:36, domain:"Civil / Political", trend:"↑", lat:47.2, lon:19.5 },
  { iso:"300", name:"Greece", level:"MODERATE", score:33, domain:"Economic", trend:"→", lat:39.1, lon:21.8 },
  { iso:"100", name:"Bulgaria", level:"MODERATE", score:32, domain:"Civil / Political", trend:"→", lat:42.7, lon:25.5 },
  { iso:"191", name:"Croatia", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:45.1, lon:15.2 },
  { iso:"705", name:"Slovenia", level:"MODERATE", score:25, domain:"Economic", trend:"→", lat:46.1, lon:14.8 },
  { iso:"008", name:"Albania", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:41.1, lon:20.2 },
  { iso:"807", name:"North Macedonia", level:"MODERATE", score:29, domain:"Civil / Political", trend:"→", lat:41.6, lon:21.7 },
  { iso:"499", name:"Montenegro", level:"MODERATE", score:29, domain:"Civil / Political", trend:"→", lat:42.7, lon:19.4 },
  { iso:"703", name:"Slovakia", level:"MODERATE", score:31, domain:"Civil / Political", trend:"↑", lat:48.7, lon:19.7 },
  { iso:"203", name:"Czechia", level:"MODERATE", score:28, domain:"Economic", trend:"→", lat:49.8, lon:15.5 },
  { iso:"040", name:"Austria", level:"MODERATE", score:27, domain:"Civil / Political", trend:"↑", lat:47.5, lon:14.6 },
  { iso:"756", name:"Switzerland", level:"MODERATE", score:22, domain:"Economic", trend:"→", lat:46.8, lon:8.2 },
  { iso:"528", name:"Netherlands", level:"MODERATE", score:27, domain:"Civil / Political", trend:"↑", lat:52.3, lon:5.3 },
  { iso:"056", name:"Belgium", level:"MODERATE", score:29, domain:"Civil / Political", trend:"→", lat:50.5, lon:4.5 },
  { iso:"208", name:"Denmark", level:"MODERATE", score:20, domain:"Economic", trend:"→", lat:56.3, lon:9.5 },
  { iso:"752", name:"Sweden", level:"MODERATE", score:24, domain:"Civil / Political", trend:"↑", lat:62.2, lon:17.6 },
  { iso:"578", name:"Norway", level:"MODERATE", score:18, domain:"Economic", trend:"→", lat:64.5, lon:17.9 },
  { iso:"246", name:"Finland", level:"MODERATE", score:22, domain:"Civil / Political", trend:"→", lat:64.9, lon:25.8 },
  { iso:"372", name:"Ireland", level:"MODERATE", score:22, domain:"Civil / Political", trend:"↑", lat:53.4, lon:-7.9 },
  { iso:"352", name:"Iceland", level:"MODERATE", score:15, domain:"Climate", trend:"→", lat:64.9, lon:-19.0 },
  { iso:"470", name:"Malta", level:"MODERATE", score:22, domain:"Civil / Political", trend:"→", lat:35.9, lon:14.4 },
  { iso:"196", name:"Cyprus", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:35.1, lon:33.4 },
  { iso:"400", name:"Jordan", level:"MODERATE", score:35, domain:"Economic", trend:"↑", lat:30.6, lon:36.8 },
  { iso:"414", name:"Kuwait", level:"MODERATE", score:28, domain:"Civil / Political", trend:"↑", lat:29.3, lon:47.7 },
  { iso:"784", name:"UAE", level:"MODERATE", score:26, domain:"Cyber / Tech", trend:"→", lat:23.4, lon:53.8 },
  { iso:"634", name:"Qatar", level:"MODERATE", score:24, domain:"Civil / Political", trend:"→", lat:25.4, lon:51.2 },
  { iso:"512", name:"Oman", level:"MODERATE", score:22, domain:"Economic", trend:"→", lat:21.0, lon:57.0 },
  { iso:"048", name:"Bahrain", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:26.1, lon:50.6 },
  { iso:"398", name:"Kazakhstan", level:"MODERATE", score:32, domain:"Civil / Political", trend:"↑", lat:48.0, lon:67.0 },
  { iso:"860", name:"Uzbekistan", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:41.4, lon:64.6 },
  { iso:"795", name:"Turkmenistan", level:"MODERATE", score:35, domain:"Civil / Political", trend:"→", lat:40.6, lon:58.4 },
  { iso:"417", name:"Kyrgyzstan", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:41.2, lon:74.8 },
  { iso:"704", name:"Vietnam", level:"MODERATE", score:27, domain:"Civil / Political", trend:"→", lat:16.6, lon:106.3 },
  { iso:"764", name:"Thailand", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:15.9, lon:100.9 },
  { iso:"116", name:"Cambodia", level:"MODERATE", score:31, domain:"Civil / Political", trend:"↑", lat:12.6, lon:104.9 },
  { iso:"458", name:"Malaysia", level:"MODERATE", score:26, domain:"Civil / Political", trend:"→", lat:4.2, lon:109.5 },
  { iso:"496", name:"Mongolia", level:"MODERATE", score:25, domain:"Economic", trend:"→", lat:46.9, lon:103.8 },
  { iso:"096", name:"Brunei", level:"MODERATE", score:18, domain:"Civil / Political", trend:"→", lat:4.9, lon:114.9 },
  { iso:"626", name:"Timor-Leste", level:"MODERATE", score:30, domain:"Economic", trend:"→", lat:-8.9, lon:125.7 },
  { iso:"524", name:"Nepal", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:28.4, lon:84.1 },
  { iso:"064", name:"Bhutan", level:"MODERATE", score:15, domain:"Economic", trend:"→", lat:27.5, lon:90.4 },
  { iso:"012", name:"Algeria", level:"MODERATE", score:33, domain:"Civil / Political", trend:"→", lat:28.0, lon:1.7 },
  { iso:"504", name:"Morocco", level:"MODERATE", score:29, domain:"Civil / Political", trend:"→", lat:31.8, lon:-5.4 },
  { iso:"788", name:"Tunisia", level:"MODERATE", score:36, domain:"Civil / Political", trend:"↑", lat:33.9, lon:9.5 },
  { iso:"686", name:"Senegal", level:"MODERATE", score:27, domain:"Civil / Political", trend:"↑", lat:14.5, lon:-14.5 },
  { iso:"288", name:"Ghana", level:"MODERATE", score:30, domain:"Economic", trend:"↑", lat:7.9, lon:-1.2 },
  { iso:"384", name:"Côte d'Ivoire", level:"MODERATE", score:27, domain:"Civil / Political", trend:"→", lat:7.5, lon:-5.6 },
  { iso:"646", name:"Rwanda", level:"MODERATE", score:33, domain:"Civil / Political", trend:"↑", lat:-1.9, lon:29.9 },
  { iso:"834", name:"Tanzania", level:"MODERATE", score:26, domain:"Civil / Political", trend:"→", lat:-6.4, lon:34.9 },
  { iso:"894", name:"Zambia", level:"MODERATE", score:28, domain:"Economic", trend:"↑", lat:-13.1, lon:27.9 },
  { iso:"454", name:"Malawi", level:"MODERATE", score:29, domain:"Economic", trend:"↑", lat:-13.3, lon:34.3 },
  { iso:"450", name:"Madagascar", level:"MODERATE", score:30, domain:"Climate", trend:"↑", lat:-19.4, lon:46.7 },
  { iso:"516", name:"Namibia", level:"MODERATE", score:22, domain:"Economic", trend:"→", lat:-22.3, lon:17.1 },
  { iso:"072", name:"Botswana", level:"MODERATE", score:22, domain:"Economic", trend:"↑", lat:-22.3, lon:24.7 },
  { iso:"426", name:"Lesotho", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:-29.6, lon:28.2 },
  { iso:"748", name:"Eswatini", level:"MODERATE", score:32, domain:"Civil / Political", trend:"↑", lat:-26.5, lon:31.5 },
  { iso:"478", name:"Mauritania", level:"MODERATE", score:31, domain:"Civil / Political", trend:"→", lat:20.3, lon:-10.9 },
  { iso:"270", name:"Gambia", level:"MODERATE", score:25, domain:"Civil / Political", trend:"→", lat:13.5, lon:-15.6 },
  { iso:"694", name:"Sierra Leone", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:8.5, lon:-11.8 },
  { iso:"430", name:"Liberia", level:"MODERATE", score:27, domain:"Civil / Political", trend:"→", lat:6.4, lon:-9.4 },
  { iso:"204", name:"Benin", level:"MODERATE", score:29, domain:"Civil / Political", trend:"↑", lat:9.3, lon:2.3 },
  { iso:"768", name:"Togo", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:8.6, lon:0.8 },
  { iso:"624", name:"Guinea-Bissau", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:11.9, lon:-15.2 },
  { iso:"178", name:"Republic of Congo", level:"MODERATE", score:30, domain:"Civil / Political", trend:"→", lat:-0.2, lon:15.8 },
  { iso:"226", name:"Equatorial Guinea", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:1.7, lon:10.3 },
  { iso:"174", name:"Comoros", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:-11.9, lon:43.4 },
  { iso:"262", name:"Djibouti", level:"MODERATE", score:29, domain:"Civil / Political", trend:"→", lat:11.8, lon:42.6 },
  { iso:"480", name:"Mauritius", level:"MODERATE", score:20, domain:"Economic", trend:"→", lat:-20.2, lon:57.6 },
  { iso:"214", name:"Dominican Republic", level:"MODERATE", score:28, domain:"Civil / Political", trend:"→", lat:18.7, lon:-70.2 },
  { iso:"388", name:"Jamaica", level:"MODERATE", score:31, domain:"Civil / Political", trend:"→", lat:18.1, lon:-77.3 },
  { iso:"600", name:"Paraguay", level:"MODERATE", score:25, domain:"Civil / Political", trend:"→", lat:-23.4, lon:-58.4 },
  { iso:"858", name:"Uruguay", level:"MODERATE", score:16, domain:"Economic", trend:"→", lat:-32.5, lon:-55.8 },
  { iso:"152", name:"Chile", level:"MODERATE", score:25, domain:"Civil / Political", trend:"→", lat:-35.7, lon:-71.5 },
  { iso:"068", name:"Bolivia", level:"MODERATE", score:32, domain:"Civil / Political", trend:"↑", lat:-16.3, lon:-64.6 },
  { iso:"328", name:"Guyana", level:"MODERATE", score:25, domain:"Economic", trend:"↑", lat:4.9, lon:-58.9 },
  { iso:"740", name:"Suriname", level:"MODERATE", score:28, domain:"Economic", trend:"→", lat:4.0, lon:-55.9 },
  { iso:"188", name:"Costa Rica", level:"MODERATE", score:18, domain:"Economic", trend:"→", lat:9.7, lon:-83.8 },
  { iso:"591", name:"Panama", level:"MODERATE", score:23, domain:"Civil / Political", trend:"↑", lat:8.4, lon:-80.1 },
  { iso:"084", name:"Belize", level:"MODERATE", score:24, domain:"Civil / Political", trend:"→", lat:17.2, lon:-88.5 },
  { iso:"222", name:"El Salvador", level:"MODERATE", score:26, domain:"Civil / Political", trend:"↓", lat:13.8, lon:-88.9 },
  { iso:"780", name:"Trinidad and Tobago", level:"MODERATE", score:27, domain:"Civil / Political", trend:"→", lat:10.7, lon:-61.2 },
  { iso:"554", name:"New Zealand", level:"MODERATE", score:17, domain:"Climate", trend:"→", lat:-40.9, lon:174.9 },
  { iso:"090", name:"Solomon Islands", level:"MODERATE", score:30, domain:"Civil / Political", trend:"↑", lat:-8.9, lon:160.2 },
  { iso:"242", name:"Fiji", level:"MODERATE", score:24, domain:"Civil / Political", trend:"→", lat:-17.7, lon:178.1 },
  { iso:"548", name:"Vanuatu", level:"MODERATE", score:25, domain:"Climate", trend:"↑", lat:-15.4, lon:166.9 },
  { iso:"024", name:"Angola", level:"MODERATE", score:32, domain:"Civil / Political", trend:"→", lat:-11.2, lon:17.9 },
  { iso:"044", name:"Bahamas", level:"MODERATE", score:24, domain:"Climate", trend:"↑", lat:24.3, lon:-76.0 },
  { iso:"158", name:"Taiwan", level:"HIGH", score:81, domain:"Civil / Political", trend:"↑", lat:23.7, lon:121.0 },
  { iso:"238", name:"Falkland Islands", level:"MODERATE", score:20, domain:"Civil / Political", trend:"→", lat:-51.8, lon:-59.5 },
  { iso:"304", name:"Greenland", level:"MODERATE", score:30, domain:"Civil / Political", trend:"↑", lat:72.0, lon:-40.0 },
  { iso:"442", name:"Luxembourg", level:"MODERATE", score:16, domain:"Economic", trend:"→", lat:49.8, lon:6.1 },
  { iso:"540", name:"New Caledonia", level:"MODERATE", score:30, domain:"Civil / Political", trend:"↑", lat:-20.9, lon:165.6 },
  { iso:"620", name:"Portugal", level:"MODERATE", score:26, domain:"Economic", trend:"→", lat:39.6, lon:-7.8 },
  { iso:"630", name:"Puerto Rico", level:"MODERATE", score:28, domain:"Economic", trend:"→", lat:18.2, lon:-66.6 },
  { iso:"732", name:"Western Sahara", level:"ELEVATED", score:48, domain:"Civil / Political", trend:"↑", lat:24.2, lon:-12.9 },
  { iso:"xk", name:"Kosovo", level:"ELEVATED", score:49, domain:"Civil / Political", trend:"↑", lat:42.6, lon:20.9 },
  { iso:"nc-cy", name:"N. Cyprus", level:"ELEVATED", score:45, domain:"Civil / Political", trend:"→", lat:35.2, lon:33.6 },
  { iso:"so-sl", name:"Somaliland", level:"HIGH", score:65, domain:"Civil / Political", trend:"→", lat:9.6, lon:45.1 },
  { iso:"010", name:"Antarctica", level:"MODERATE", score:15, domain:"Climate", trend:"↑", lat:-80.0, lon:0.0 },
  { iso:"316", name:"Guam", level:"HIGH", score:72, domain:"Civil / Political", trend:"↑", lat:13.5, lon:144.8 },
  { iso:"258", name:"French Polynesia", level:"MODERATE", score:25, domain:"Civil / Political", trend:"→", lat:-17.6, lon:-149.4 },
  { iso:"584", name:"Marshall Islands", level:"HIGH", score:68, domain:"Climate", trend:"↑", lat:7.1, lon:171.1 },
  { iso:"585", name:"Micronesia", level:"MODERATE", score:32, domain:"Climate", trend:"↑", lat:7.4, lon:150.6 },
  { iso:"520", name:"Nauru", level:"MODERATE", score:22, domain:"Climate", trend:"↑", lat:-0.5, lon:166.9 },
  { iso:"798", name:"Tuvalu", level:"HIGH", score:70, domain:"Climate", trend:"↑", lat:-8.5, lon:179.2 },
  { iso:"598", name:"Papua New Guinea", level:"HIGH", score:67, domain:"Civil / Political", trend:"↑", lat:-6.3, lon:143.9 },
];

export const riskByIso = Object.fromEntries(
  COUNTRY_RISK.map((c) => [c.iso, c])
) as Record<string, CountryRiskSummary>;

export const riskStats = {
  critical:  COUNTRY_RISK.filter((c) => c.level === "CRITICAL").length,
  high:      COUNTRY_RISK.filter((c) => c.level === "HIGH").length,
  elevated:  COUNTRY_RISK.filter((c) => c.level === "ELEVATED").length,
  moderate:  COUNTRY_RISK.filter((c) => c.level === "MODERATE").length,
  total:     COUNTRY_RISK.length,
};

export const CRITICAL_HOTSPOTS = COUNTRY_RISK.filter((c) => c.level === "CRITICAL");
