// lib/watchtower/news-feed-pins.ts

export interface NewsFeedPin {
  id:        string;
  lat:       number;
  lng:       number;
  headline:  string;
  source:    string;
  summary:   string;
  sourceUrl: string;
  category:  "war" | "economic" | "nuclear" | "health" | "climate" | "political";
  tier:      "t4" | "t3" | "t2";
  date:      string;
  region?:   string;
}

export const NEWS_FEED_PINS: NewsFeedPin[] = [
  {
    id:        "N01",
    lat:        49.8,
    lng:        36.2,
    headline:  "Russia Renews Kharkiv Offensive",
    source:    "Reuters",
    summary:   "Russian forces launch renewed push toward Kharkiv following spring thaw. Ukrainian defenses strained along 80km front as ammunition reserves run critically low.",
    sourceUrl: "https://reuters.com",
    category:  "war",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N02",
    lat:        31.5,
    lng:        34.5,
    headline:  "Gaza Infrastructure at Total Collapse",
    source:    "UN OCHA",
    summary:   "UN declares 96% of Gaza water infrastructure non-functional. Hospital fuel stocks exhausted. 2.1 million people face acute famine conditions.",
    sourceUrl: "https://unocha.org",
    category:  "health",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N03",
    lat:        24.0,
    lng:       122.0,
    headline:  "PLAN 72-Hour Taiwan Strait Drill",
    source:    "AP",
    summary:   "China's PLA Navy launches largest Taiwan Strait exercise since 2023. Live-fire zones encircle the island. US Carrier Strike Group 11 repositioned to the Philippine Sea.",
    sourceUrl: "https://apnews.com",
    category:  "war",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N04",
    lat:        15.0,
    lng:        43.0,
    headline:  "Houthi Strikes Resume, Red Sea Insurance Crisis",
    source:    "Bloomberg",
    summary:   "Ceasefire collapse triggers new wave of Houthi anti-ship missile attacks. Three commercial vessels struck this week. Cargo insurance premiums up 40% in 48 hours.",
    sourceUrl: "https://bloomberg.com",
    category:  "war",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N05",
    lat:        35.7,
    lng:        51.4,
    headline:  "Iran Enrichment at 84% — IAEA Blocked",
    source:    "FT",
    summary:   "Iran enriches uranium to 84% purity at Fordow facility — one step from weapons-grade 90%. IAEA inspectors denied access for the 6th consecutive month.",
    sourceUrl: "https://ft.com",
    category:  "nuclear",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N06",
    lat:        39.0,
    lng:       125.8,
    headline:  "North Korea Opens ICBM Test Window",
    source:    "38North",
    summary:   "Satellite imagery confirms Hwasong-19 ICBM preparations at Sohae launch facility. US Indo-Pacific Command placed on heightened alert posture.",
    sourceUrl: "https://38north.org",
    category:  "nuclear",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N07",
    lat:        34.5,
    lng:        73.0,
    headline:  "India-Pakistan LOC Violations at 5-Year High",
    source:    "The Hindu",
    summary:   "Line of Control ceasefire violations reach highest level since 2021. Artillery exchanges in Azad Kashmir. Both sides conducting nuclear force readiness exercises.",
    sourceUrl: "https://thehindu.com",
    category:  "war",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N08",
    lat:        52.4,
    lng:         4.9,
    headline:  "EU Gas Prices Surge 28% — Energy Emergency",
    source:    "FT",
    summary:   "Dutch TTF natural gas futures spike on polar vortex event. European storage at 18% capacity — below critical threshold. 8 EU member states declare energy poverty emergencies.",
    sourceUrl: "https://ft.com",
    category:  "economic",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N09",
    lat:        39.9,
    lng:       116.4,
    headline:  "China Hits US Semiconductors with 145% Tariff",
    source:    "WSJ",
    summary:   "Beijing retaliates with 145% tariff on US semiconductor exports in escalating trade war. TSMC caught in crossfire as US fab access restrictions tighten simultaneously.",
    sourceUrl: "https://wsj.com",
    category:  "economic",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N10",
    lat:       -34.6,
    lng:       -58.4,
    headline:  "Argentina Peso Collapses 31% — IMF Emergency",
    source:    "Bloomberg",
    summary:   "Argentine peso loses 31% against blue-chip rate in one week. IMF emergency review triggered. Milei government faces critical $4.2B debt servicing deadline.",
    sourceUrl: "https://bloomberg.com",
    category:  "economic",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N11",
    lat:        15.6,
    lng:        32.5,
    headline:  "Sudan SAF Launches Major Khartoum Offensive",
    source:    "Reuters",
    summary:   "Sudan Armed Forces launch push to retake Khartoum from RSF paramilitary. Heaviest urban combat in 12 months. 9 million displaced — world's largest displacement crisis.",
    sourceUrl: "https://reuters.com",
    category:  "war",
    tier:      "t4",
    date:      "MAR 2026",
  },
  {
    id:        "N12",
    lat:        12.4,
    lng:        -1.5,
    headline:  "Burkina Faso Junta Expels French Forces",
    source:    "AFP",
    summary:   "Burkina Faso military junta orders remaining French special forces to leave within 72 hours. Wagner Group advisors fill the security vacuum. Sahel arc destabilization accelerating.",
    sourceUrl: "https://afp.com",
    category:  "political",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N13",
    lat:        11.0,
    lng:       119.0,
    headline:  "Philippines-China South China Sea Standoff",
    source:    "Reuters",
    summary:   "Chinese coast guard deploys water cannons on Philippine supply vessel for 8th time this quarter. US invokes Mutual Defense Treaty. Emergency ASEAN summit called.",
    sourceUrl: "https://reuters.com",
    category:  "war",
    tier:      "t3",
    date:      "MAR 2026",
  },
  {
    id:        "N14",
    lat:        25.7,
    lng:      -100.3,
    headline:  "Fentanyl Seizures Hit Record at US-Mexico Border",
    source:    "AP",
    summary:   "US Customs seizes 4.2 tonnes of fentanyl in two weeks — largest ever. Cartel state capture confirmed by US intelligence in 3 Mexican border states.",
    sourceUrl: "https://apnews.com",
    category:  "political",
    tier:      "t2",
    date:      "MAR 2026",
  },
  {
    id:        "N15",
    lat:        41.9,
    lng:        12.5,
    headline:  "Italy BTP-Bund Spread Hits Crisis Level — 280bps",
    source:    "FT",
    summary:   "Italian sovereign spread widens to post-2012 crisis levels. ECB bond-buying capacity questioned as Germany blocks additional QE. €2.8T debt pile triggers institutional alarm.",
    sourceUrl: "https://ft.com",
    category:  "economic",
    tier:      "t3",
    date:      "MAR 2026",
  },
];
