// lib/provisioner/catalog.ts
import type { TierRequirement, GradeLevel } from "@/types/treasury";
import { REA_EXTENDED } from "./rea-extended";

export type ProductCategory =
  | "communications"
  | "medical"
  | "energy"
  | "mobility"
  | "water"
  | "security"
  | "shelter"
  | "real_estate";

export interface SafetyScore {
  nuclearDistance:    number;  // 0–100: proximity away from likely strike zones
  disasterRisk:       number;  // 0–100: inverse (100 = minimal natural disaster exposure)
  populationDensity:  number;  // 0–100: inverse (100 = extremely low density / rural)
  politicalStability: number;  // 0–100: GPI rank + freedom index composite
}

export interface Product {
  id:              string;
  sku:             string;
  name:            string;
  brand:           string;
  category:        ProductCategory;
  grade:           GradeLevel;
  gradeComposite:  number;
  tier:            TierRequirement;
  priceUsd:        number;           // USD cents
  priceUsdc:       number;           // USDC (6 decimal places as float)
  highTicket:      boolean;          // true → Solana USDC rail
  inStock:         boolean;
  criticalFlag:    boolean;
  spec:            string;
  buildNote:       string;
  stripePriceId?:  string;           // Stripe Price ID (low-ticket)
  imageSlug:       string;
  location?:       string;           // "New Zealand — South Island"
  safetyScore?:    SafetyScore;      // present for real_estate category
  listingNote?:    string;           // replaces buildNote label copy for real estate
  priceDisplay?:   string;           // override price string e.g. "$350,000"
  externalUrl?:    string;           // official brand/manufacturer page — shown as helper link
  gearLayers?: {
    durability:           number;   // 0-100: physical resilience + lifespan
    grid_independence:    number;   // 0-100: functions without grid power
    field_repairability:  number;   // 0-100: fixable without specialized tools
    value_density:        number;   // 0-100: utility per dollar
    supply_chain:         number;   // 0-100: ease of sourcing / replacement
  };
}

// ── Catalog ─────────────────────────────────────────────────────────────
// priceUsd is in cents. All Solana-rail items have highTicket: true.
// The Stripe Price IDs are placeholders — replace with live Stripe dashboard IDs.

export const CATALOG: Product[] = [
  // ── COMMUNICATIONS ─────────────────────────────────────────────────
  {
    id:"garmin-inreach-mini2", sku:"COM-001", name:"Garmin inReach Mini 2",
    brand:"Garmin", category:"communications", grade:"A", gradeComposite:96,
    tier:"T1", priceUsd:34999, priceUsdc:349.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Sends and receives text messages via satellite from anywhere on Earth — no cell signal required. Includes one-button SOS that contacts emergency services, live GPS tracking, and weather forecasts.",
    buildNote:"1 per adult. Activate a Garmin satellite plan separately — plans start at $14.95/mo.",
    stripePriceId:"price_1TE8ROAQV21Gk5Rw5Vk2i6r5",
    imageSlug:"garmin-inreach-mini2",
    externalUrl:"https://www.garmin.com/en-US/p/775983",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:85, value_density:92, supply_chain:96 },
  },
  {
    id:"baofeng-uv5r-5pk", sku:"COM-002", name:"Baofeng UV-5R ×5 Pack",
    brand:"Baofeng", category:"communications", grade:"B", gradeComposite:81,
    tier:"T1", priceUsd:13999, priceUsdc:139.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Two-way radio that works on dual VHF/UHF bands with 5 watts of output power. Can access 400+ frequencies. Rechargeable lithium battery included.",
    buildNote:"Pre-program channels before any crisis. A ham radio license is recommended.",
    stripePriceId:"price_1TE8RPAQV21Gk5Rw5f9LZOZh",
    imageSlug:"baofeng-uv5r",
    externalUrl:"https://www.baofengradio.com/products/uv-5r",
    gearLayers:{ durability:70, grid_independence:95, field_repairability:80, value_density:95, supply_chain:82 },
  },
  {
    id:"starlink-mini", sku:"COM-005", name:"Starlink Mini Portable",
    brand:"SpaceX", category:"communications", grade:"A", gradeComposite:94,
    tier:"T2", priceUsd:59900, priceUsdc:599.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Portable satellite internet dish (1 kg) delivering 100+ Mbps internet speed from anywhere on Earth. Enables full community communications when all other infrastructure is down.",
    buildNote:"Tier 2 community backbone. Activate a Starlink subscription at starlink.com — plans from $50/mo.",
    stripePriceId:"price_1TETh3AQV21Gk5RwbSTJCVzr",
    imageSlug:"starlink-mini",
    externalUrl:"https://www.starlink.com/hardware",
    gearLayers:{ durability:95, grid_independence:98, field_repairability:88, value_density:96, supply_chain:96 },
  },

  // ── MEDICAL ────────────────────────────────────────────────────────
  {
    id:"nar-ifak", sku:"MED-001", name:"NAR IFAK Trauma Kit",
    brand:"North American Rescue", category:"medical", grade:"A", gradeComposite:99,
    tier:"T1", priceUsd:7499, priceUsdc:74.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Military-grade individual trauma kit. Includes a SOF-T Wide tourniquet (to stop limb bleeding), a HyFin chest seal (for chest wounds), compressed gauze, and trauma dressing. Built to US military TCCC (combat casualty care) standards.",
    buildNote:"1 per adult go-bag. Non-negotiable.",
    stripePriceId:"price_1TE8RQAQV21Gk5RwD4EMtRVJ",
    imageSlug:"nar-ifak",
    externalUrl:"https://www.narescue.com/individual-first-aid-kit-ifak",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:98, value_density:98, supply_chain:98 },
  },
  {
    id:"myfak-advanced", sku:"MED-002", name:"MyMedic MYFAK Advanced Kit",
    brand:"MyMedic", category:"medical", grade:"A", gradeComposite:97,
    tier:"T1", priceUsd:15999, priceUsdc:159.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"150+ piece first aid kit covering trauma, wound care, and medications. A complete first-tier household medical kit for handling injuries and illness when a hospital is not accessible.",
    buildNote:"1 per household minimum.",
    stripePriceId:"price_1TE8RSAQV21Gk5Rwpn4aFKf2",
    imageSlug:"myfak-advanced",
    externalUrl:"https://mymedic.com/products/the-myfak-pro-kit",
    gearLayers:{ durability:95, grid_independence:100, field_repairability:95, value_density:96, supply_chain:94 },
  },
  {
    id:"quikclot-3pk", sku:"MED-003", name:"QuikClot Combat Gauze ×3",
    brand:"Z-Medica", category:"medical", grade:"A", gradeComposite:99,
    tier:"T1", priceUsd:7499, priceUsdc:74.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Special gauze containing a clotting agent that stops life-threatening bleeding in 3–5 minutes. Stays effective for 3 years on the shelf.",
    buildNote:"Keep 6+ units total. Replace at 80% of shelf life.",
    stripePriceId:"price_1TE8RTAQV21Gk5RwjHqpR9kF",
    imageSlug:"quikclot",
    externalUrl:"https://www.zmedica.com/collections/quikclot",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:98, value_density:99, supply_chain:98 },
  },

  // ── ENERGY ─────────────────────────────────────────────────────────
  {
    id:"jackery-1000plus", sku:"ENE-001", name:"Jackery Explorer 1000 Plus",
    brand:"Jackery", category:"energy", grade:"B", gradeComposite:88,
    tier:"T1", priceUsd:99900, priceUsdc:999.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Portable battery (1,264 watt-hours / LFP chemistry). Can power a refrigerator for 4 hours, a CPAP medical device for 14 hours, or charge a phone 100+ times. Fully recharges in 2 hours. Rated for 2,000 full charge cycles.",
    buildNote:"Tier 1 go-bag power station. Add a Nomad 100 solar panel for solar charging input.",
    stripePriceId:"price_1TEUHCAQV21Gk5RwrTg0OO0i",
    imageSlug:"jackery-1000plus",
    externalUrl:"https://www.jackery.com/products/explorer-1000-plus-portable-power-station",
    gearLayers:{ durability:88, grid_independence:96, field_repairability:72, value_density:90, supply_chain:85 },
  },
  {
    id:"ecoflow-delta-pro", sku:"ENE-002", name:"EcoFlow DELTA Pro",
    brand:"EcoFlow", category:"energy", grade:"A", gradeComposite:95,
    tier:"T2", priceUsd:220000, priceUsdc:2200.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Large portable battery (3,600 watt-hours / LFP chemistry) with a 2,400W AC output. Can run most household appliances. Expandable to 25 kWh total storage with add-on batteries. Rated for 3,500 charge cycles.",
    buildNote:"Tier 2 sanctuary essential. Pair with a Renogy 400W solar panel array.",
    stripePriceId:"price_1TEUHEAQV21Gk5RwQ7lnNsGR",
    imageSlug:"ecoflow-delta-pro",
    externalUrl:"https://www.ecoflow.com/us/delta-pro-portable-power-station.html",
    gearLayers:{ durability:95, grid_independence:99, field_repairability:88, value_density:96, supply_chain:90 },
  },
  {
    id:"renogy-400w-kit", sku:"ENE-003", name:"Renogy 400W Solar Kit",
    brand:"Renogy", category:"energy", grade:"B", gradeComposite:87,
    tier:"T2", priceUsd:58000, priceUsdc:580.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Four 100-watt monocrystalline solar panels and a 40-amp MPPT charge controller. In average sunlight, generates about 1.6 kWh of electricity per day. Can be expanded to a 2 kW array.",
    buildNote:"Starting point for off-grid solar power. Scales to a 2 kW array.",
    stripePriceId:"price_1TEUHGAQV21Gk5RwU6Kj9KXD",
    imageSlug:"renogy-400w",
    externalUrl:"https://www.renogy.com/400-watt-12-volt-monocrystalline-solar-starter-kit/",
    gearLayers:{ durability:84, grid_independence:98, field_repairability:76, value_density:88, supply_chain:80 },
  },

  // ── MOBILITY ────────────────────────────────────────────────────────
  {
    id:"wavian-jerry-4pk", sku:"MOB-001", name:"Wavian NATO Jerry Can ×4",
    brand:"Wavian", category:"mobility", grade:"A", gradeComposite:98,
    tier:"T1", priceUsd:15999, priceUsdc:159.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"UN-certified steel fuel containers, 5 gallons each. Airtight seal prevents leaks and vapor. Will not crack, leak, or fail under normal conditions. Built to NATO military standards.",
    buildNote:"Keep all cans full at all times. Rotate fuel every quarter using PRI-G fuel stabilizer.",
    stripePriceId:"price_1TE8RUAQV21Gk5RwwZCWF6PZ",
    imageSlug:"wavian-jerry",
    externalUrl:"https://wavian.us/",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:95, value_density:98, supply_chain:92 },
  },
  {
    id:"noco-gb40-2pk", sku:"MOB-002", name:"NOCO Boost Plus GB40 ×2",
    brand:"NOCO", category:"mobility", grade:"A", gradeComposite:96,
    tier:"T1", priceUsd:19999, priceUsdc:199.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Compact lithium jump starter that delivers 1,000 peak amps — enough to start vehicles with engines up to 6L gas or 3L diesel. Includes USB charging for phones.",
    buildNote:"Keep one in every vehicle. Recharge the unit every quarter.",
    stripePriceId:"price_1TE8RWAQV21Gk5RwXsoQMDtM",
    imageSlug:"noco-gb40",
    externalUrl:"https://no-co.com/gb40.html",
    gearLayers:{ durability:95, grid_independence:98, field_repairability:88, value_density:96, supply_chain:95 },
  },

  // ── WATER ───────────────────────────────────────────────────────────
  {
    id:"berkey-big-berkey", sku:"WAT-001", name:"Berkey Big Berkey",
    brand:"Berkey", category:"water", grade:"A", gradeComposite:97,
    tier:"T1", priceUsd:27999, priceUsdc:279.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Gravity-fed ceramic water filter (no power needed) that processes 8.5 liters per hour. Removes viruses, bacteria, and heavy metals from untreated water.",
    buildNote:"Primary household water filter. Replace filter elements per manufacturer specifications.",
    stripePriceId:"price_1TE8RXAQV21Gk5RwO8LlZhQi",
    imageSlug:"berkey-big",
    externalUrl:"https://berkeyfilters.com/products/big-berkey",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:95, value_density:94, supply_chain:90 },
  },
  {
    id:"sawyer-squeeze", sku:"WAT-002", name:"Sawyer Squeeze Filter",
    brand:"Sawyer", category:"water", grade:"B", gradeComposite:84,
    tier:"T1", priceUsd:3499, priceUsdc:34.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Hollow-fiber water filter with a lifetime capacity of 100,000 gallons. Filters particles down to 0.1 microns at no power cost. Can be backflushed to restore flow.",
    buildNote:"1 per go-bag. Does not remove viruses — pair with a SteriPen UV purifier in areas with biological contamination.",
    stripePriceId:"price_1TE8RZAQV21Gk5RwkOTw1WTa",
    imageSlug:"sawyer-squeeze",
    externalUrl:"https://sawyer.com/products/sawyer-squeeze-filter-system/",
    gearLayers:{ durability:70, grid_independence:100, field_repairability:80, value_density:92, supply_chain:78 },
  },

  // ── COMMUNICATIONS (continued) ─────────────────────────────────────
  {
    id:"midland-er310", sku:"COM-003", name:"Midland ER310 Emergency Radio",
    brand:"Midland", category:"communications", grade:"B", gradeComposite:85,
    tier:"T1", priceUsd:7999, priceUsdc:79.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Emergency radio that receives AM/FM stations and NOAA weather alerts. Can be powered by hand-cranking, a built-in solar panel, or USB-C. Includes an SOS flashlight and a 2,000 mAh backup battery.",
    buildNote:"One per location. Needs no subscription. Hand-cranking powers the radio during a complete communications blackout.",
    stripePriceId:"price_placeholder_COM003",
    imageSlug:"midland-er310",
    externalUrl:"https://www.midlandusa.com/products/er310",
    gearLayers:{ durability:80, grid_independence:98, field_repairability:72, value_density:88, supply_chain:80 },
  },
  {
    id:"motorola-t800-6pk", sku:"COM-004", name:"Motorola T800 FRS Radio ×6",
    brand:"Motorola", category:"communications", grade:"B", gradeComposite:79,
    tier:"T1", priceUsd:12999, priceUsdc:129.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"License-free FRS (Family Radio Service) two-way radios with 22 channels. Range up to 35 miles in open terrain. NOAA weather alert reception. Rechargeable lithium battery.",
    buildNote:"No license required. Pre-program household communication channels before any crisis.",
    stripePriceId:"price_placeholder_COM004",
    imageSlug:"motorola-t800",
    externalUrl:"https://www.motorolasolutions.com/en_us/consumer/two-way-radios/talkabout/t800.html",
    gearLayers:{ durability:75, grid_independence:88, field_repairability:62, value_density:88, supply_chain:82 },
  },

  // ── MEDICAL (continued) ─────────────────────────────────────────────
  {
    id:"israeli-bandage-10pk", sku:"MED-004", name:"Israeli Emergency Bandage ×10",
    brand:"PerSys Medical", category:"medical", grade:"A", gradeComposite:98,
    tier:"T1", priceUsd:4499, priceUsdc:44.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"6-inch emergency pressure bandage that can be applied one-handed to control serious bleeding. Sterile. 5-year shelf life.",
    buildNote:"2 per go-bag minimum. Standard combat dressing for penetrating wounds (TCCC).",
    stripePriceId:"price_placeholder_MED004",
    imageSlug:"israeli-bandage",
    externalUrl:"https://www.persysmedical.com/products/emergency-bandage",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:96, value_density:98, supply_chain:96 },
  },
  {
    id:"celox-granules-5pk", sku:"MED-005", name:"Celox Hemostatic Granules ×5",
    brand:"Celox", category:"medical", grade:"A", gradeComposite:97,
    tier:"T1", priceUsd:5999, priceUsdc:59.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Chitosan-based clotting granules that stop serious bleeding in 30 seconds. Works even in cold conditions where body temperature is low. 3-year shelf life.",
    buildNote:"Complements QuikClot gauze. Use for wounds where packing with gauze is not practical.",
    stripePriceId:"price_placeholder_MED005",
    imageSlug:"celox-granules",
    externalUrl:"https://www.celox.co.uk/products/celox-granules/",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:94, value_density:96, supply_chain:94 },
  },

  // ── ENERGY (continued) ──────────────────────────────────────────────
  {
    id:"goal-zero-yeti-200x", sku:"ENE-004", name:"Goal Zero Yeti 200X",
    brand:"Goal Zero", category:"energy", grade:"A", gradeComposite:91,
    tier:"T1", priceUsd:29900, priceUsdc:299.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Small portable battery (187 watt-hours / LFP chemistry) with a 200W AC inverter, USB-A, and USB-C ports. Solar-compatible input. Weighs 2 kg. Recharges from the wall in 2 hours.",
    buildNote:"Go-bag power station for phones, radios, and CPAP machines. Pairs with the Nomad 20 solar panel.",
    stripePriceId:"price_placeholder_ENE004",
    imageSlug:"goal-zero-yeti-200x",
    externalUrl:"https://www.goalzero.com/products/yeti-200x",
    gearLayers:{ durability:90, grid_independence:96, field_repairability:82, value_density:92, supply_chain:90 },
  },

  // ── MOBILITY (continued) ────────────────────────────────────────────
  {
    id:"garmin-gpsmap-67", sku:"MOB-003", name:"Garmin GPSMAP 67 Handheld",
    brand:"Garmin", category:"mobility", grade:"A", gradeComposite:95,
    tier:"T1", priceUsd:39900, priceUsdc:399.00, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Multi-system GPS unit (works with GPS, GLONASS, and other satellite networks) with a 16-hour battery life. Pre-loaded topographic maps. IPX7 waterproof (survives submersion). Works without cell service.",
    buildNote:"Primary navigation tool when cell phone infrastructure is unavailable. Pre-load offline topographic maps for your region.",
    stripePriceId:"price_placeholder_MOB003",
    imageSlug:"garmin-gpsmap-67",
    externalUrl:"https://www.garmin.com/en-US/p/765156",
    gearLayers:{ durability:96, grid_independence:98, field_repairability:85, value_density:90, supply_chain:95 },
  },

  // ── WATER (continued) ───────────────────────────────────────────────
  {
    id:"waterbob-2pk", sku:"WAT-003", name:"WaterBOB Emergency Bladder ×2",
    brand:"WaterBOB", category:"water", grade:"B", gradeComposite:83,
    tier:"T1", priceUsd:6999, priceUsdc:69.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Food-grade plastic bladder (100 gallons capacity) that fits inside a standard bathtub. Fills from the tap in 20 minutes. BPA-free.",
    buildNote:"Fill immediately at the first sign of water disruption. 100 gallons = a 50-day supply for one adult.",
    stripePriceId:"price_placeholder_WAT003",
    imageSlug:"waterbob",
    externalUrl:"https://waterbob.com/",
    gearLayers:{ durability:72, grid_independence:100, field_repairability:68, value_density:88, supply_chain:80 },
  },
  {
    id:"potable-aqua-6pk", sku:"WAT-004", name:"Potable Aqua Iodine Tabs ×6",
    brand:"Potable Aqua", category:"water", grade:"C", gradeComposite:71,
    tier:"T1", priceUsd:2999, priceUsdc:29.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Iodine water purification tablets. Each 50-tablet pack treats 25 liters of water. A neutralizer tablet is included to remove the iodine taste. 4-year shelf life.",
    buildNote:"Backup to your primary water filter. Effective against bacteria and viruses. Does not remove heavy metals.",
    stripePriceId:"price_placeholder_WAT004",
    imageSlug:"potable-aqua",
    externalUrl:"https://potableaqua.com/",
    gearLayers:{ durability:52, grid_independence:95, field_repairability:60, value_density:78, supply_chain:72 },
  },

  // ── SECURITY ────────────────────────────────────────────────────────
  {
    id:"reolink-rlc810a-4pk", sku:"SEC-001", name:"Reolink RLC-810A ×4",
    brand:"Reolink", category:"security", grade:"B", gradeComposite:86,
    tier:"T2", priceUsd:31999, priceUsdc:319.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"4K resolution IP security camera with 30-meter night vision. Powered over ethernet (PoE) cable. Stores footage locally to a network video recorder (NVR) — no cloud account required.",
    buildNote:"Minimum 4-camera perimeter setup. Pair with a local NVR recorder (no cloud dependency).",
    stripePriceId:"price_1TE8RaAQV21Gk5RwuYAccWXC",
    imageSlug:"reolink-810a",
    externalUrl:"https://reolink.com/us/product/rlc-810a/",
    gearLayers:{ durability:86, grid_independence:84, field_repairability:82, value_density:92, supply_chain:88 },
  },
  {
    id:"faraday-bag-xl", sku:"SEC-003", name:"Mission Darkness Faraday Bag XL",
    brand:"Mission Darkness", category:"security", grade:"C", gradeComposite:72,
    tier:"T1", priceUsd:5999, priceUsdc:59.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Shielding bag designed to block EMP (electromagnetic pulse), HEMP (high-altitude EMP), and solar flare radiation. Fits a tablet, radio, and storage drives. Laboratory tested.",
    buildNote:"Grade C: effective for electromagnetic shielding only. Not suitable for long-term electronics storage.",
    stripePriceId:"price_1TE8RbAQV21Gk5RwcQUclk8w",
    imageSlug:"faraday-xl",
    externalUrl:"https://www.mosequipment.com/products/mission-darkness-non-window-laptop-faraday-bag",
    gearLayers:{ durability:60, grid_independence:100, field_repairability:48, value_density:72, supply_chain:65 },
  },
  {
    id:"surefire-g2x-3pk", sku:"SEC-002", name:"SureFire G2X Tactical LED ×3",
    brand:"SureFire", category:"security", grade:"B", gradeComposite:88,
    tier:"T1", priceUsd:15999, priceUsdc:159.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Tactical LED flashlight with 800-lumen maximum output and a low-power 15-lumen setting. Nitrolon polymer body is lightweight and shockproof. Uses CR123A lithium batteries. IPX7 waterproof.",
    buildNote:"1 per household member. Store with go-bag. Keep spare batteries in a Faraday bag.",
    stripePriceId:"price_placeholder_SEC002",
    imageSlug:"surefire-g2x",
    externalUrl:"https://www.surefire.com/g2x-tactical/",
    gearLayers:{ durability:92, grid_independence:88, field_repairability:82, value_density:86, supply_chain:84 },
  },

  // ── SHELTER ─────────────────────────────────────────────────────────
  {
    id:"sol-bivvy-4pk", sku:"SHE-001", name:"SOL Emergency Bivvy ×4",
    brand:"SOL", category:"shelter", grade:"A", gradeComposite:93,
    tier:"T1", priceUsd:8499, priceUsdc:84.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Reflective mylar sleeping bag that retains 90% of your body heat. Waterproof. Weighs 3.8 oz each. Reusable.",
    buildNote:"1 per go-bag. Packs to the size of a fist. Viable in freezing temperatures even without a sleeping bag.",
    stripePriceId:"price_placeholder_SHE001",
    imageSlug:"sol-bivvy",
    externalUrl:"https://www.surviveoutdoorslonger.com/products/escape-bivvy",
    gearLayers:{ durability:90, grid_independence:100, field_repairability:84, value_density:98, supply_chain:90 },
  },
  {
    id:"kelty-cosmic-20", sku:"SHE-002", name:"Kelty Cosmic 20° Down Sleeping Bag",
    brand:"Kelty", category:"shelter", grade:"A", gradeComposite:90,
    tier:"T1", priceUsd:19900, priceUsdc:199.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"600-fill-power down sleeping bag rated to 20°F (-7°C). Weighs 3 lbs. Comes with a compression sack. DWR (water-resistant) outer shell.",
    buildNote:"One per adult for cold-weather shelter when the power grid is down. Pair with a SOL bivvy as an outer vapor barrier.",
    stripePriceId:"price_placeholder_SHE002",
    imageSlug:"kelty-cosmic-20",
    externalUrl:"https://www.kelty.com/cosmic-20/",
    gearLayers:{ durability:88, grid_independence:100, field_repairability:80, value_density:90, supply_chain:86 },
  },
  {
    id:"titan-survival-tarp", sku:"SHE-003", name:"Titan Multi-Use Survival Tarp",
    brand:"Titan", category:"shelter", grade:"B", gradeComposite:80,
    tier:"T1", priceUsd:4999, priceUsdc:49.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Heavy-duty tarp (12×8 ft) that can serve as a rain fly, ground cloth, heat reflector, or shade shelter. Weighs 1.9 lbs.",
    buildNote:"Pack 2 per group. The reflective silver side doubles as an emergency signaling panel.",
    stripePriceId:"price_placeholder_SHE003",
    imageSlug:"titan-tarp",
    externalUrl:"https://titansurvival.com/products/multi-use-tarp",
    gearLayers:{ durability:68, grid_independence:100, field_repairability:72, value_density:80, supply_chain:68 },
  },

  // ── COMMUNICATIONS (continued) ─────────────────────────────────────
  {
    id:"iridium-go-exec", sku:"COM-006", name:"Iridium GO! Exec Satellite Hotspot",
    brand:"Iridium", category:"communications", grade:"A", gradeComposite:93,
    tier:"T2", priceUsd:129900, priceUsdc:1299.00, highTicket:true, inStock:true,
    criticalFlag:true,
    spec:"Portable satellite Wi-Fi hotspot that turns your existing smartphone into a satellite phone — no cell signal needed anywhere on Earth. Supports voice calls, SOS messaging, and basic data. Covers all 7 continents including polar regions.",
    buildNote:"1 per group. Requires an Iridium satellite voice plan starting at $34.95/mo. Far cheaper than a dedicated sat-phone.",
    stripePriceId:"price_placeholder_COM006",
    imageSlug:"iridium-go-exec",
    externalUrl:"https://www.iridium.com/products/iridium-go-exec/",
    gearLayers:{ durability:94, grid_independence:100, field_repairability:78, value_density:88, supply_chain:85 },
  },
  {
    id:"anytone-d878uvii", sku:"COM-007", name:"Anytone AT-D878UVII Plus Ham Radio",
    brand:"Anytone", category:"communications", grade:"B", gradeComposite:83,
    tier:"T1", priceUsd:18900, priceUsdc:189.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Dual-band DMR digital and analog handheld radio. Digital mode extends effective range and enables encrypted private channels. Stores 3,000 contacts and 4,000 channels. Programmable via USB from a PC. Rechargeable 3,100 mAh battery.",
    buildNote:"Requires a Technician ham radio license. Significant upgrade over Baofeng UV-5R in range, audio quality, and digital capability.",
    stripePriceId:"price_placeholder_COM007",
    imageSlug:"anytone-d878uvii",
    externalUrl:"https://www.anytone.net/product/at-d878uvii-plus/",
    gearLayers:{ durability:85, grid_independence:95, field_repairability:70, value_density:88, supply_chain:78 },
  },
  {
    id:"meshtastic-rak-4pk", sku:"COM-008", name:"Meshtastic LoRa Mesh Node ×4",
    brand:"RAK Wireless", category:"communications", grade:"B", gradeComposite:79,
    tier:"T1", priceUsd:14900, priceUsdc:149.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Four low-power LoRa radio nodes that form an encrypted, off-grid text message network across several kilometers — no internet, cell signal, or subscription required. Battery-powered. Open-source Meshtastic firmware. Community-expandable range.",
    buildNote:"Place 1 node per building or vehicle. Each node extends range. Ideal for grid-down neighborhood coordination networks.",
    stripePriceId:"price_placeholder_COM008",
    imageSlug:"meshtastic-rak",
    externalUrl:"https://store.rakwireless.com/products/wisblock-starter-kit",
    gearLayers:{ durability:80, grid_independence:98, field_repairability:75, value_density:90, supply_chain:72 },
  },

  // ── MEDICAL (continued) ─────────────────────────────────────────────
  {
    id:"cat-gen7-4pk", sku:"MED-006", name:"CAT Gen7 Combat Tourniquet ×4",
    brand:"North American Rescue", category:"medical", grade:"A", gradeComposite:100,
    tier:"T1", priceUsd:11999, priceUsdc:119.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"The Combat Application Tourniquet (CAT) Generation 7 is the only tourniquet approved by the US military for self-application. Can be applied one-handed in under 30 seconds. Has saved more lives than any other tourniquet in combat history. Windlass design locks in place.",
    buildNote:"1 per adult go-bag, minimum. Do not substitute with cheaper alternatives — field tests show most off-brand tourniquets fail under pressure.",
    stripePriceId:"price_placeholder_MED006",
    imageSlug:"cat-gen7",
    externalUrl:"https://www.narescue.com/combat-application-tourniquet-c-a-t",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:98, value_density:99, supply_chain:98 },
  },
  {
    id:"dripdrop-ors-24pk", sku:"MED-007", name:"DripDrop ORS Hydration Packets ×24",
    brand:"DripDrop", category:"medical", grade:"A", gradeComposite:95,
    tier:"T1", priceUsd:2999, priceUsdc:29.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"WHO-formula oral rehydration salts. Each packet treats 1 liter of water to replace electrolytes lost from diarrhea, vomiting, heat, or physical exertion. Three times more effective than plain water at preventing dehydration shock. 3-year shelf life.",
    buildNote:"Critical for diarrheal illness — the #1 cause of death in grid-down scenarios. 24 packets = one person for several weeks of moderate illness.",
    stripePriceId:"price_placeholder_MED007",
    imageSlug:"dripdrop-ors",
    externalUrl:"https://www.dripdrop.com/",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:100, value_density:99, supply_chain:95 },
  },
  {
    id:"amk-trauma-pro", sku:"MED-008", name:"Adventure Medical Kits Trauma Pro",
    brand:"Adventure Medical Kits", category:"medical", grade:"B", gradeComposite:88,
    tier:"T1", priceUsd:8999, priceUsdc:89.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Two-person wilderness trauma kit covering fractures (SAM splint), wounds (hemostatic dressing and pressure bandage), dislocations, burns, and blisters. 18 medication types included. Designed for scenarios where professional medical care is more than 1 hour away.",
    buildNote:"Complements the NAR IFAK for sustained care beyond immediate trauma control. Good secondary kit for a vehicle or base camp.",
    stripePriceId:"price_placeholder_MED008",
    imageSlug:"amk-trauma-pro",
    externalUrl:"https://www.adventuremedicalkits.com/products/trauma-pro",
    gearLayers:{ durability:95, grid_independence:100, field_repairability:92, value_density:90, supply_chain:88 },
  },

  // ── ENERGY (continued) ──────────────────────────────────────────────
  {
    id:"biolite-campstove2plus", sku:"ENE-005", name:"BioLite CampStove 2+",
    brand:"BioLite", category:"energy", grade:"A", gradeComposite:91,
    tier:"T1", priceUsd:14900, priceUsdc:149.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Burns dry sticks, pinecones, or any biomass — no gas canister or fuel required ever. A built-in thermoelectric generator converts fire heat into 3 watts of USB power for charging phones and radios. Weighs 1 lb. Cooks a full meal in under 10 minutes.",
    buildNote:"The only stove that generates electricity from fire. Eliminates dependence on stored propane. Pair with a 100-watt solar panel for dual charging capability.",
    stripePriceId:"price_placeholder_ENE005",
    imageSlug:"biolite-campstove2",
    externalUrl:"https://www.bioliteenergy.com/products/campstove-2-plus",
    gearLayers:{ durability:88, grid_independence:100, field_repairability:82, value_density:92, supply_chain:85 },
  },
  {
    id:"nitecore-nb10000-gen2", sku:"ENE-006", name:"Nitecore NB10000 Gen2 Solar Power Bank",
    brand:"Nitecore", category:"energy", grade:"B", gradeComposite:82,
    tier:"T1", priceUsd:6499, priceUsdc:64.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"10,000 mAh slim power bank with a built-in solar panel for emergency top-up charging in sunlight. Two USB-A and one USB-C port. Weighs 175g — fits in any pocket. Fully charges a phone 2.5 times. Can trickle-charge from ambient sunlight over 24 hours.",
    buildNote:"1 per adult go-bag. Lightweight emergency charging when primary power stations are not portable enough.",
    stripePriceId:"price_placeholder_ENE006",
    imageSlug:"nitecore-nb10000",
    externalUrl:"https://www.nitecore.com/product/nb10000-gen2",
    gearLayers:{ durability:80, grid_independence:88, field_repairability:55, value_density:84, supply_chain:82 },
  },
  {
    id:"champion-3500w-dual-fuel", sku:"ENE-007", name:"Champion 3500W Dual-Fuel Generator",
    brand:"Champion Power Equipment", category:"energy", grade:"B", gradeComposite:85,
    tier:"T2", priceUsd:59900, priceUsdc:599.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"3,500-watt generator that runs on gasoline or propane (LPG). Propane mode eliminates fuel degradation during long-term storage. 9-hour runtime at 50% load. Electric start. 68 dBA noise at 23 feet — quieter than most generators in this class.",
    buildNote:"Tier 2 base power for a household or community. Always store a minimum 20 lb propane tank full. Gasoline deteriorates in 3 months without stabilizer; propane stores indefinitely.",
    stripePriceId:"price_placeholder_ENE007",
    imageSlug:"champion-3500w",
    externalUrl:"https://www.championpowerequipment.com/product/100891/",
    gearLayers:{ durability:82, grid_independence:90, field_repairability:78, value_density:86, supply_chain:84 },
  },

  // ── MOBILITY (continued) ────────────────────────────────────────────
  {
    id:"pri-g-stabilizer-4pk", sku:"MOB-004", name:"PRI-G Fuel Stabilizer ×4 (32 oz)",
    brand:"PRI Products", category:"mobility", grade:"A", gradeComposite:97,
    tier:"T1", priceUsd:7999, priceUsdc:79.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Gasoline storage treatment that keeps stored fuel combustion-ready for 24+ months (untreated gas degrades in 3 months). One 32 oz bottle treats up to 256 gallons. Proven in military and emergency management fuel programs. Also restores old, degraded fuel.",
    buildNote:"Treat all stored fuel at fill-up. If you have jerry cans, stored generators, or emergency vehicles, this is non-negotiable. Rotate stocks every 24 months.",
    stripePriceId:"price_placeholder_MOB004",
    imageSlug:"pri-g-stabilizer",
    externalUrl:"https://www.priproducts.com/product/pri-g-gasoline-treatment/",
    gearLayers:{ durability:100, grid_independence:100, field_repairability:100, value_density:99, supply_chain:96 },
  },
  {
    id:"tred-gt-recovery-2pk", sku:"MOB-005", name:"TRED GT Vehicle Recovery Boards ×2",
    brand:"TRED Pro", category:"mobility", grade:"A", gradeComposite:94,
    tier:"T1", priceUsd:29900, priceUsdc:299.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"High-density polymer traction boards that allow a single driver to self-recover a vehicle stuck in mud, sand, or snow without outside help. Rated to 4 tonnes per board. Stackable. Mountable to most vehicle roof racks or rear-door carriers.",
    buildNote:"Keep mounted to any vehicle used for evacuation routes. Critical in regions with poor roads or winter conditions. Works on 2WD and 4WD vehicles.",
    stripePriceId:"price_placeholder_MOB005",
    imageSlug:"tred-gt-recovery",
    externalUrl:"https://tredpro.com/",
    gearLayers:{ durability:96, grid_independence:100, field_repairability:88, value_density:90, supply_chain:82 },
  },
  {
    id:"morakniv-companion-4pk", sku:"MOB-006", name:"Morakniv Companion Fixed Blade ×4",
    brand:"Morakniv", category:"mobility", grade:"B", gradeComposite:86,
    tier:"T1", priceUsd:7999, priceUsdc:79.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Full-tang high-carbon steel fixed blade (4.1-inch / 3.2mm thick spine) rated to 2.5× the stress tolerance of standard knives. Rubber grip. Multi-use field tool for cutting, shelter building, food prep, and first aid tasks. One per group member.",
    buildNote:"1 per adult. Carbon steel holds a sharper edge than stainless but requires light oiling to prevent rust. Sharpen with a whetstone.",
    stripePriceId:"price_placeholder_MOB006",
    imageSlug:"morakniv-companion",
    externalUrl:"https://morakniv.se/en/product/companion-heavy-duty-orange/",
    gearLayers:{ durability:92, grid_independence:100, field_repairability:90, value_density:96, supply_chain:92 },
  },

  // ── WATER (continued) ───────────────────────────────────────────────
  {
    id:"steripen-adventurer-uv", sku:"WAT-005", name:"SteriPen Adventurer UV Purifier",
    brand:"SteriPen", category:"water", grade:"B", gradeComposite:87,
    tier:"T1", priceUsd:9999, priceUsdc:99.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"UV light wand that neutralizes 99.9999% of viruses, bacteria, and protozoa in a 1-liter water bottle in under 90 seconds. Uses no chemicals. 8,000-treatment lifespan. Runs on 2× CR123A lithium batteries. Required when using the Sawyer Squeeze filter in areas with viral contamination.",
    buildNote:"Critical companion to mechanical filters — hollow-fiber filters like the Sawyer Squeeze do NOT remove viruses. Use SteriPen after filtering for complete protection.",
    stripePriceId:"price_placeholder_WAT005",
    imageSlug:"steripen-adventurer",
    externalUrl:"https://www.steripen.com/adventurer-optic/",
    gearLayers:{ durability:82, grid_independence:88, field_repairability:58, value_density:88, supply_chain:82 },
  },
  {
    id:"lifestraw-personal-6pk", sku:"WAT-006", name:"LifeStraw Personal Filter ×6",
    brand:"LifeStraw", category:"water", grade:"B", gradeComposite:83,
    tier:"T1", priceUsd:8999, priceUsdc:89.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Personal hollow-fiber filter that removes 99.999% of waterborne bacteria and 99.9% of parasites from any freshwater source. 1,000-gallon (4,000-liter) lifetime. Weighs 2 oz. No batteries, no moving parts, no chemicals. Drink directly from any stream, puddle, or container.",
    buildNote:"1 per go-bag, 1 per person. The lightest water treatment option available. Does not remove viruses — pair with SteriPen WAT-005 in high-risk areas.",
    stripePriceId:"price_placeholder_WAT006",
    imageSlug:"lifestraw-personal",
    externalUrl:"https://www.lifestraw.com/products/lifestraw-personal",
    gearLayers:{ durability:72, grid_independence:100, field_repairability:70, value_density:94, supply_chain:88 },
  },

  // ── SECURITY (continued) ────────────────────────────────────────────
  {
    id:"flir-scout-tk", sku:"SEC-004", name:"FLIR Scout TK Thermal Monocular",
    brand:"Teledyne FLIR", category:"security", grade:"A", gradeComposite:92,
    tier:"T2", priceUsd:54900, priceUsdc:549.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Pocket-sized thermal camera that detects body heat signatures at up to 100 meters — through total darkness, fog, smoke, and light foliage. 5-hour battery life. Records video and stills to micro-SD. No IR illuminator needed (emits no visible or IR light, so it cannot be spotted by opposing optics).",
    buildNote:"For perimeter monitoring when power is out. A single unit watching an approach route gives early warning of unauthorized movement. Pairs with the Reolink camera system for 24/7 coverage.",
    stripePriceId:"price_placeholder_SEC004",
    imageSlug:"flir-scout-tk",
    externalUrl:"https://www.flir.com/products/scout-tk/",
    gearLayers:{ durability:90, grid_independence:94, field_repairability:62, value_density:86, supply_chain:78 },
  },
  {
    id:"sabre-crossfire-4pk", sku:"SEC-005", name:"SABRE Red Crossfire Gel Spray ×4",
    brand:"SABRE", category:"security", grade:"B", gradeComposite:82,
    tier:"T1", priceUsd:5999, priceUsdc:59.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Police-strength OC (pepper) and CS (tear gas) combination in a gel carrier. 18-foot range. 35 bursts per canister. Gel formula reduces blowback in wind. Safety twist-lock prevents accidental discharge. 4-year shelf life. Used by law enforcement agencies.",
    buildNote:"1 per adult. Keep near an entry point and in every go-bag. Gel carrier is important — aerosol sprays can blow back onto the user in wind conditions.",
    stripePriceId:"price_placeholder_SEC005",
    imageSlug:"sabre-crossfire",
    externalUrl:"https://www.sabrered.com/pages/crossfire",
    gearLayers:{ durability:85, grid_independence:100, field_repairability:88, value_density:88, supply_chain:90 },
  },
  {
    id:"verbatim-4tb-usb-ssd", sku:"SEC-006", name:"Verbatim 4TB Portable SSD",
    brand:"Verbatim", category:"security", grade:"B", gradeComposite:78,
    tier:"T1", priceUsd:8999, priceUsdc:89.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"4TB ruggedized external SSD for offline encrypted data archiving. USB-C connection. Stores all critical documents, medical records, maps, manuals, and media in a pocket-sized drive. 256-bit AES hardware encryption. Shock, vibration, and temperature resistant.",
    buildNote:"Store copies of: ID and passports, medical records, financial documents, offline maps (AllTrails, OsmAnd), survival manuals (FM 21-76), and communication frequencies. Keep inside a Faraday bag (SEC-003).",
    stripePriceId:"price_placeholder_SEC006",
    imageSlug:"verbatim-4tb-ssd",
    externalUrl:"https://www.verbatim.com/",
    gearLayers:{ durability:88, grid_independence:92, field_repairability:45, value_density:85, supply_chain:88 },
  },

  // ── SHELTER (continued) ─────────────────────────────────────────────
  {
    id:"mountain-house-30day", sku:"SHE-004", name:"Mountain House 30-Day Food Supply",
    brand:"Mountain House", category:"shelter", grade:"A", gradeComposite:94,
    tier:"T1", priceUsd:19999, priceUsdc:199.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"30-day emergency food supply for one adult. Freeze-dried meals with a verified 30-year shelf life. No refrigeration needed — add boiling water and eat in 10 minutes. 2,000+ calories per day across breakfast, lunch, and dinner variety. Oxygen-absorber packaging.",
    buildNote:"1 kit per adult per month of planned reserves. Start with a 30-day supply per person. Tastes significantly better than MREs. Rotate every 5 years for best quality.",
    stripePriceId:"price_placeholder_SHE004",
    imageSlug:"mountain-house-30day",
    externalUrl:"https://mountainhouse.com/products/just-in-case-30-day-emergency-food-supply",
    gearLayers:{ durability:98, grid_independence:95, field_repairability:100, value_density:92, supply_chain:88 },
  },
  {
    id:"camp-chef-explorer-2x", sku:"SHE-005", name:"Camp Chef Explorer Two-Burner Stove",
    brand:"Camp Chef", category:"shelter", grade:"B", gradeComposite:84,
    tier:"T1", priceUsd:17900, priceUsdc:179.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Propane two-burner stove producing 30,000 BTU total. Accepts both 1 lb disposable canisters and 20 lb tanks via adapter hose. Wind guards included. Leveling feet adjust for uneven terrain. Compatible with cast iron cookware and Dutch ovens.",
    buildNote:"Primary cooking solution when the kitchen is unavailable. Store a minimum of two 20 lb propane tanks full (48+ hours of cooking per tank at normal use). Never use propane indoors.",
    stripePriceId:"price_placeholder_SHE005",
    imageSlug:"camp-chef-explorer",
    externalUrl:"https://www.campchef.com/products/explorer-2-burner-stove",
    gearLayers:{ durability:86, grid_independence:94, field_repairability:82, value_density:88, supply_chain:86 },
  },
  {
    id:"sea-to-summit-spark-spi", sku:"SHE-006", name:"Sea to Summit Spark SpI Sleeping Bag",
    brand:"Sea to Summit", category:"shelter", grade:"B", gradeComposite:86,
    tier:"T1", priceUsd:22900, priceUsdc:229.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"850-fill-power down sleeping bag rated to 45°F (7°C) for three-season use. Weighs 12.5 oz — the lightest warm sleeping bag available at this price point. Compresses to a 1-liter stuff sack. DWR outer shell sheds light moisture. For go-bag scenarios where every gram matters.",
    buildNote:"For when the SOL bivvy (SHE-001) is not warm enough. Pair together in cold weather: bivvy over the sleeping bag adds 15°F of warmth, making this combination rated to 30°F.",
    stripePriceId:"price_placeholder_SHE006",
    imageSlug:"sea-to-summit-spark",
    externalUrl:"https://www.seatosummit.com/products/sleeping-bags/",
    gearLayers:{ durability:84, grid_independence:100, field_repairability:78, value_density:88, supply_chain:82 },
  },

  // ── COMMUNICATIONS (batch 3) ────────────────────────────────────────
  {
    id:"midland-mxt500", sku:"COM-009", name:"Midland MXT500 MicroMobile GMRS Radio",
    brand:"Midland", category:"communications", grade:"B", gradeComposite:81,
    tier:"T1", priceUsd:14900, priceUsdc:149.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"50-watt vehicle-mounted GMRS radio with up to 65-mile range in open terrain. Broadcasts to all Midland T-series handheld radios. No license exam required — GMRS license is $35 for 10 years, covers the whole family. 15 high-power channels plus 8 repeater channels.",
    buildNote:"Mount one in every vehicle for convoy and household coordination. GMRS license is family-wide and costs $35 total — no exam, no renewal for 10 years. Far more powerful than handheld FRS radios.",
    stripePriceId:"price_placeholder_COM009",
    imageSlug:"midland-mxt500",
    externalUrl:"https://www.midlandusa.com/products/mxt500",
    gearLayers:{ durability:85, grid_independence:92, field_repairability:72, value_density:86, supply_chain:80 },
  },
  {
    id:"tecsun-pl990x", sku:"COM-010", name:"Tecsun PL-990x Shortwave Receiver",
    brand:"Tecsun", category:"communications", grade:"B", gradeComposite:80,
    tier:"T1", priceUsd:17900, priceUsdc:179.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"High-sensitivity AM, FM, shortwave, and SSB radio receiver. Picks up international broadcasts, military weather stations, aviation bands, and ham radio transmissions — all without internet. Analog tuning dial plus digital display. Built-in rechargeable battery. External antenna port.",
    buildNote:"Receive BBC World Service, VOA, and government emergency broadcasts when the internet is down. Not for transmitting — receive only. Pair with a simple long-wire external antenna for dramatically better reception.",
    stripePriceId:"price_placeholder_COM010",
    imageSlug:"tecsun-pl990x",
    externalUrl:"https://tecsunworld.com/products/tecsun-pl-990x",
    gearLayers:{ durability:80, grid_independence:96, field_repairability:62, value_density:82, supply_chain:75 },
  },
  {
    id:"spot-x-2way", sku:"COM-011", name:"SPOT X 2-Way Satellite Messenger",
    brand:"Globalstar", category:"communications", grade:"A", gradeComposite:90,
    tier:"T1", priceUsd:24900, priceUsdc:249.00, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Two-way satellite text messenger with a dedicated QWERTY keyboard. Send and receive messages from anywhere on Earth with no cell signal. One-button SOS contacts a 24/7 emergency response center. Real-time GPS tracking share. Runs 240 hours on a full charge.",
    buildNote:"Lower-cost satellite messaging alternative to Garmin inReach. Monthly plans start at $11.95. Best for solo travelers or as a backup messenger for group members who don't carry the primary inReach.",
    stripePriceId:"price_placeholder_COM011",
    imageSlug:"spot-x-2way",
    externalUrl:"https://www.findmespot.com/en-us/products/spot-x",
    gearLayers:{ durability:90, grid_independence:100, field_repairability:72, value_density:88, supply_chain:82 },
  },

  // ── MEDICAL (batch 3) ────────────────────────────────────────────────
  {
    id:"3m-n95-8210-20pk", sku:"MED-009", name:"3M N95 NIOSH Respirator ×20",
    brand:"3M", category:"medical", grade:"A", gradeComposite:96,
    tier:"T1", priceUsd:4999, priceUsdc:49.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"NIOSH-certified N95 particulate respirator (3M 8210) that filters 95% of airborne particles including wildfire smoke, dust, and aerosolized pathogens. Tested and certified to NIOSH 42 CFR Part 84 standards. Soft inner material for extended wear.",
    buildNote:"20 per household minimum. Critical for pandemic response, wildfire smoke, and industrial chemical events. N95 is the lowest effective protection level — P100 is stronger for chemical scenarios. Replace after each day of heavy use.",
    stripePriceId:"price_placeholder_MED009",
    imageSlug:"3m-n95-8210",
    externalUrl:"https://www.3m.com/3M/en_US/respiratory-protection-us/",
    gearLayers:{ durability:88, grid_independence:100, field_repairability:100, value_density:98, supply_chain:95 },
  },
  {
    id:"sam-splint-combo-4pk", sku:"MED-010", name:"SAM Splint 36-Inch ×4",
    brand:"SAM Medical", category:"medical", grade:"A", gradeComposite:94,
    tier:"T1", priceUsd:3999, priceUsdc:39.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Foam-padded aluminum splint (36 inch) that can be shaped and cut to immobilize any fracture from finger to femur. No plaster, no water, no setting time. Standard across military and wilderness medicine protocols. Reusable. Folds flat.",
    buildNote:"2 full-length and 2 short (cut to wrist/arm length) per household. Broken bones in a grid-down scenario require immobilization for weeks — a SAM splint is the lightest way to achieve that.",
    stripePriceId:"price_placeholder_MED010",
    imageSlug:"sam-splint",
    externalUrl:"https://www.sammedical.com/products/sam-splint",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:100, value_density:98, supply_chain:94 },
  },
  {
    id:"where-there-is-no-doctor", sku:"MED-011", name:"Where There Is No Doctor (Book)",
    brand:"Hesperian Health Guides", category:"medical", grade:"A", gradeComposite:98,
    tier:"T1", priceUsd:2499, priceUsdc:24.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"The most widely used community health manual on Earth — translated into 100+ languages, used in 180+ countries. Covers diagnosis and treatment of common illnesses, childbirth, wound care, nutrition, and disease prevention without hospital access. 512 pages. Used by village health workers globally.",
    buildNote:"The single most important medical purchase for grid-down scenarios. Knowledge does not run out of batteries. Also download the free PDF version to your offline SSD archive (SEC-006).",
    stripePriceId:"price_placeholder_MED011",
    imageSlug:"where-there-is-no-doctor",
    externalUrl:"https://www.hesperian.org/books-and-resources/where-there-is-no-doctor/",
    gearLayers:{ durability:92, grid_independence:100, field_repairability:100, value_density:100, supply_chain:98 },
  },

  // ── ENERGY (batch 3) ────────────────────────────────────────────────
  {
    id:"bluetti-ac200max", sku:"ENE-008", name:"Bluetti AC200MAX Power Station",
    brand:"BLUETTI", category:"energy", grade:"A", gradeComposite:94,
    tier:"T2", priceUsd:149900, priceUsdc:1499.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Large portable battery station (2,048 watt-hours / LFP chemistry) with a 2,200W AC output. Expandable to 8,192 Wh with add-on batteries. 16 output ports including AC, DC, USB-A, USB-C, and a car port. Rated 3,500+ charge cycles. Can be charged by solar, AC wall, and car simultaneously.",
    buildNote:"Alternative to the EcoFlow DELTA Pro. Expandable battery capacity is ideal for a fixed shelter location. Pair with a 400W+ solar array for sustained off-grid power.",
    stripePriceId:"price_placeholder_ENE008",
    imageSlug:"bluetti-ac200max",
    externalUrl:"https://www.bluettipower.com/products/ac200max",
    gearLayers:{ durability:94, grid_independence:99, field_repairability:86, value_density:92, supply_chain:88 },
  },
  {
    id:"renogy-200w-suitcase", sku:"ENE-009", name:"Renogy 200W Foldable Solar Panel",
    brand:"Renogy", category:"energy", grade:"B", gradeComposite:86,
    tier:"T1", priceUsd:29900, priceUsdc:299.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Two 100W monocrystalline solar panels in a hinged suitcase design with a built-in 20A MPPT charge controller. Generates up to 800 Wh per day in good sunlight. Connects directly to any Jackery, Bluetti, or EcoFlow station with the included MC4 adapter cable. Folds to briefcase size.",
    buildNote:"Portable solar input for Jackery 1000 Plus (ENE-001) or Bluetti AC200MAX (ENE-008). Provides roughly 3–4 full phone charges per hour of peak sunlight.",
    stripePriceId:"price_placeholder_ENE009",
    imageSlug:"renogy-200w-foldable",
    externalUrl:"https://www.renogy.com/200-watt-foldable-solar-panel/",
    gearLayers:{ durability:82, grid_independence:100, field_repairability:74, value_density:88, supply_chain:82 },
  },
  {
    id:"nitecore-i8-charger", sku:"ENE-010", name:"Nitecore i8 8-Slot Battery Charger",
    brand:"Nitecore", category:"energy", grade:"B", gradeComposite:84,
    tier:"T1", priceUsd:3499, priceUsdc:34.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"8-slot universal battery charger that handles AA, AAA, C, D, 18650, 26650, and all common rechargeable formats simultaneously. Auto-detects each battery's chemistry (NiMH, Li-ion) and charges at the correct rate. Includes a USB output to charge devices from batteries in the charger.",
    buildNote:"Critical for a household running on rechargeable batteries. Pair with a stockpile of Eneloop Pro AA batteries and 18650 cells for flashlights, radios, and medical devices.",
    stripePriceId:"price_placeholder_ENE010",
    imageSlug:"nitecore-i8",
    externalUrl:"https://www.nitecore.com/product/i8",
    gearLayers:{ durability:86, grid_independence:85, field_repairability:70, value_density:90, supply_chain:88 },
  },

  // ── MOBILITY (batch 3) ──────────────────────────────────────────────
  {
    id:"slime-flat-repair-kit", sku:"MOB-007", name:"Slime 2X Tire Sealant + Inflator Kit ×2",
    brand:"Slime", category:"mobility", grade:"B", gradeComposite:83,
    tier:"T1", priceUsd:7499, priceUsdc:74.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Heavy-duty tire sealant that instantly fills and seals punctures up to 1/4 inch while the vehicle is moving — no jack, no spare required. Includes a 12V inflator to re-pressurize the tire after sealing. Protects against bead leaks and punctures for up to 2 years.",
    buildNote:"Keep one kit per vehicle. A flat tire is the most common mobility failure in evacuation scenarios. Seals in under 2 minutes without changing the tire.",
    stripePriceId:"price_placeholder_MOB007",
    imageSlug:"slime-flat-kit",
    externalUrl:"https://www.slime.com/",
    gearLayers:{ durability:82, grid_independence:98, field_repairability:90, value_density:90, supply_chain:88 },
  },
  {
    id:"rhino-usa-tow-strap", sku:"MOB-008", name:"Rhino USA 30-Ft Tow Strap Kit",
    brand:"Rhino USA", category:"mobility", grade:"A", gradeComposite:92,
    tier:"T1", priceUsd:4999, priceUsdc:49.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"30-foot tow strap with 31,518 lb break strength and two heavy-duty D-ring shackles included. Color-coded safety hooks and loop ends fit all standard tow hooks and hitch receivers. Stores in a carrying bag that mounts to a recovery board or bumper.",
    buildNote:"For pulling stranded vehicles or being pulled out yourself. Required companion to the TRED recovery boards (MOB-005). Keep in every vehicle.",
    stripePriceId:"price_placeholder_MOB008",
    imageSlug:"rhino-tow-strap",
    externalUrl:"https://rhinousa.com/products/tow-strap",
    gearLayers:{ durability:96, grid_independence:100, field_repairability:92, value_density:96, supply_chain:90 },
  },
  {
    id:"rad-power-radcity5", sku:"MOB-009", name:"Rad Power Bikes RadCity 5 Plus e-Bike",
    brand:"Rad Power Bikes", category:"mobility", grade:"B", gradeComposite:85,
    tier:"T2", priceUsd:199900, priceUsdc:1999.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"750W electric commuter bike with a 672 Wh battery and 45-mile range per charge. Top speed 20 mph. Integrated rear rack rated to 120 lbs. Hydraulic disc brakes. 5 levels of pedal assist — also fully rideable without motor assist. Silent operation.",
    buildNote:"Silent evacuation transport when fuel is unavailable. A fully charged bike carries one adult and 50+ lbs of gear 45 miles silently. Recharges from any wall outlet or portable power station (e.g., ENE-001).",
    stripePriceId:"price_placeholder_MOB009",
    imageSlug:"radcity5-plus",
    externalUrl:"https://www.radpowerbikes.com/products/radcity-plus-electric-commuter-bike",
    gearLayers:{ durability:80, grid_independence:88, field_repairability:72, value_density:82, supply_chain:75 },
  },

  // ── WATER (batch 3) ─────────────────────────────────────────────────
  {
    id:"waterstoragecontainer-5gal-6pk", sku:"WAT-007", name:"WaterStorageCube 5.3-Gal Containers ×6",
    brand:"WaterStorageContainers", category:"water", grade:"A", gradeComposite:91,
    tier:"T1", priceUsd:6999, priceUsdc:69.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"Stackable, food-grade HDPE water containers (5.3 gallons / 20 liters each). BPA-free. Square design stacks efficiently in any closet or garage. Includes a cap-mount spigot. Six containers = 32 gallons of stored water — a 16-day supply for one adult.",
    buildNote:"Fill immediately upon purchase with tap water and add a small amount of household bleach (8 drops per gallon) to prevent bacterial growth. Rotate every 12 months. Store away from direct sunlight.",
    stripePriceId:"price_placeholder_WAT007",
    imageSlug:"watercube-5gal",
    externalUrl:"https://www.waterstoragecontainers.us/",
    gearLayers:{ durability:88, grid_independence:100, field_repairability:92, value_density:94, supply_chain:90 },
  },
  {
    id:"aquatabs-100pk", sku:"WAT-008", name:"Aquatabs Purification Tablets ×100",
    brand:"Aquatabs", category:"water", grade:"B", gradeComposite:82,
    tier:"T1", priceUsd:1499, priceUsdc:14.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"WHO-standard sodium dichloroisocyanurate (NaDCC) tablets for water disinfection. Each tablet treats 1 liter of water in 30 minutes, killing bacteria and viruses. More stable than iodine alternatives. 5-year shelf life. Used by UNICEF, the Red Cross, and military field units worldwide.",
    buildNote:"Tertiary backup to filters and UV purifiers. 100 tablets = 100 liters of safe water. Effective against viruses where hollow-fiber filters are not. Does not remove heavy metals or chemicals.",
    stripePriceId:"price_placeholder_WAT008",
    imageSlug:"aquatabs-100pk",
    externalUrl:"https://www.aquatabs.com/",
    gearLayers:{ durability:90, grid_independence:100, field_repairability:100, value_density:96, supply_chain:92 },
  },
  {
    id:"platypus-gravityworks-4l", sku:"WAT-009", name:"Platypus GravityWorks 4L Group Filter",
    brand:"Platypus", category:"water", grade:"B", gradeComposite:88,
    tier:"T1", priceUsd:9999, priceUsdc:99.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Gravity-fed hollow-fiber filter system for groups of 4+ people. Filters 4 liters in under 2.5 minutes with zero pumping effort. Removes 99.9999% of bacteria and 99.9% of protozoa. Hangs from any branch or post. Rated for 1,500 liters before requiring replacement.",
    buildNote:"Ideal for group use at a base camp or shelter location. Faster throughput than individual filters. Does not remove viruses — combine with Aquatabs (WAT-008) or SteriPen (WAT-005) for complete coverage.",
    stripePriceId:"price_placeholder_WAT009",
    imageSlug:"platypus-gravityworks",
    externalUrl:"https://www.platy.com/",
    gearLayers:{ durability:78, grid_independence:100, field_repairability:70, value_density:88, supply_chain:82 },
  },

  // ── SECURITY (batch 3) ──────────────────────────────────────────────
  {
    id:"uniden-bc125at-scanner", sku:"SEC-007", name:"Uniden BC125AT Handheld Scanner",
    brand:"Uniden", category:"security", grade:"B", gradeComposite:79,
    tier:"T1", priceUsd:7999, priceUsdc:79.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Handheld police scanner that receives police, fire, EMS, military, aviation, and weather frequencies without a subscription. Stores 500 channels across 10 banks. Covers 25–512 MHz range. Battery or AC powered. Includes close-call RF capture for detecting nearby transmissions.",
    buildNote:"Know what first responders know. During an active crisis, monitoring local police and fire frequencies gives early warning of approaching threats, evacuation orders, and infrastructure failures. No license required to listen.",
    stripePriceId:"price_placeholder_SEC007",
    imageSlug:"uniden-bc125at",
    externalUrl:"https://www.uniden.com/products/bc125at/",
    gearLayers:{ durability:78, grid_independence:92, field_repairability:60, value_density:84, supply_chain:80 },
  },
  {
    id:"master-lock-shrouded-4pk", sku:"SEC-008", name:"Master Lock Shrouded Padlock ×4",
    brand:"Master Lock", category:"security", grade:"B", gradeComposite:83,
    tier:"T1", priceUsd:7999, priceUsdc:79.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Hardened boron carbide shackle padlock with a shrouded design that blocks bolt-cutter access on three sides. Double-locking mechanism resists picking and shimming. Rated ANSI/BHMA Grade 3. Key-retaining cylinder prevents removal when unlocked.",
    buildNote:"Secure fuel storage, generator enclosures, and supply caches. Shrouded shackle is the critical feature — a standard padlock shackle can be cut with a $15 bolt cutter in 5 seconds.",
    stripePriceId:"price_placeholder_SEC008",
    imageSlug:"master-lock-shrouded",
    externalUrl:"https://www.masterlock.com/products/padlocks/shrouded-shackle-padlocks",
    gearLayers:{ durability:92, grid_independence:100, field_repairability:88, value_density:86, supply_chain:92 },
  },
  {
    id:"pelican-1510-case", sku:"SEC-009", name:"Pelican 1510 Carry-On Hard Case",
    brand:"Pelican", category:"security", grade:"B", gradeComposite:85,
    tier:"T1", priceUsd:17500, priceUsdc:175.00, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Airline carry-on sized hard case with a watertight O-ring seal and automatic pressure equalization valve. Crushproof and dustproof. Customizable foam interior. Built-in wheels and retractable handle. Rated to IP67 (submersion proof to 1 meter).",
    buildNote:"Stores and protects your critical documents, external SSD archive, satellite messenger, emergency cash, and irreplaceable items in a case that survives anything. Foam can be cut to fit any combination of gear.",
    stripePriceId:"price_placeholder_SEC009",
    imageSlug:"pelican-1510",
    externalUrl:"https://www.pelican.com/us/en/product/cases/carry-on-case/1510/",
    gearLayers:{ durability:98, grid_independence:100, field_repairability:82, value_density:85, supply_chain:88 },
  },

  // ── SHELTER (batch 3) ────────────────────────────────────────────────
  {
    id:"uco-titan-matches-3pk", sku:"SHE-007", name:"UCO Titan Stormproof Matches ×3",
    brand:"UCO", category:"shelter", grade:"B", gradeComposite:84,
    tier:"T1", priceUsd:2099, priceUsdc:20.99, highTicket:false, inStock:true,
    criticalFlag:false,
    spec:"Extra-long waterproof matches (4 inches / 110 mm) that ignite and burn for up to 25 seconds — even after submersion in water. Each pack contains 25 matches plus 3 strikers. Works at altitude and in high wind. Flame is equivalent to a small candle.",
    buildNote:"Fire is a non-negotiable survival resource. Keep one pack in every go-bag and one in every vehicle. Always carry three fire-starting methods: lighter, stormproof matches, and a ferro rod.",
    stripePriceId:"price_placeholder_SHE007",
    imageSlug:"uco-titan-matches",
    externalUrl:"https://ucogear.com/titan-stormproof-matches-3-pack/",
    gearLayers:{ durability:88, grid_independence:100, field_repairability:100, value_density:96, supply_chain:90 },
  },
  {
    id:"mr-heater-little-buddy", sku:"SHE-008", name:"Mr. Heater Little Buddy Propane Heater",
    brand:"Mr. Heater", category:"shelter", grade:"A", gradeComposite:90,
    tier:"T1", priceUsd:8999, priceUsdc:89.99, highTicket:false, inStock:true,
    criticalFlag:true,
    spec:"3,800 BTU indoor-safe portable propane heater rated for spaces up to 95 sq ft. Built-in oxygen depletion sensor (ODS) automatically shuts off if oxygen drops below safe levels. Runs 5.6 hours on one 1 lb propane canister. Tip-over safety shutoff. Approved for indoor use.",
    buildNote:"Hypothermia kills faster than most threats. This heater is specifically rated indoor-safe — most propane heaters are NOT. Always crack a window for airflow. Store a minimum of 10 × 1 lb canisters.",
    stripePriceId:"price_placeholder_SHE008",
    imageSlug:"mr-heater-little-buddy",
    externalUrl:"https://www.mrheater.com/products/little-buddy-indoor-safe-portable-propane-heater",
    gearLayers:{ durability:88, grid_independence:96, field_repairability:80, value_density:92, supply_chain:90 },
  },
  {
    id:"husqvarna-460-rancher", sku:"SHE-009", name:"Husqvarna 460 Rancher 24\" Chainsaw",
    brand:"Husqvarna", category:"shelter", grade:"A", gradeComposite:91,
    tier:"T2", priceUsd:64900, priceUsdc:649.00, highTicket:true, inStock:true,
    criticalFlag:false,
    spec:"Professional-grade 60.3cc chainsaw with a 24-inch bar. Cuts through a 20-inch hardwood log in under 10 seconds. X-Torq engine reduces fuel consumption 20% vs. standard engines. Smart Start reduces pull-cord resistance. Compatible with ethanol-blend fuels.",
    buildNote:"Clears fallen trees blocking evacuation routes, processes firewood for winter heating, and cuts lumber for structural shelter repair. Store with a spare chain, a chain file, and bar oil. Fuel stores indefinitely with PRI-G (MOB-004).",
    stripePriceId:"price_placeholder_SHE009",
    imageSlug:"husqvarna-460-rancher",
    externalUrl:"https://www.husqvarna.com/us/chainsaws/460-rancher/967622002/",
    gearLayers:{ durability:92, grid_independence:94, field_repairability:85, value_density:88, supply_chain:86 },
  },

  // ── REAL ESTATE ──────────────────────────────────────────────────────
  {
    id:"rea-nz-south-island", sku:"REA-001",
    name:"Canterbury Station Land — South Island",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:96,
    tier:"T2", priceUsd:35000000, priceUsdc:350000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"New Zealand — South Island (Canterbury)",
    spec:"40+ acres of farmable land with an artesian well included in the title. Off-grid solar and diesel backup already installed. 90 minutes from Christchurch. No nearby seismic fault lines. Active sheep-grazing generates income.",
    buildNote:"New Zealand ranks #1 on the Global Peace Index. The remote Southern Alps location provides a natural buffer. NZ residency is available through an investment pathway.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$350,000",
    safetyScore:{ nuclearDistance:99, disasterRisk:90, populationDensity:98, politicalStability:96 },
    imageSlug:"rea-nz-south-island",
    externalUrl:"https://www.trademe.co.nz/a/property/rural",
  },
  {
    id:"rea-switzerland-graubunden", sku:"REA-002",
    name:"Alpine Farmstead — Graubünden",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:93,
    tier:"T2", priceUsd:85000000, priceUsdc:850000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Switzerland — Graubünden canton",
    spec:"6-hectare Alpine property with spring-fed water rights. Bunker-grade cellar for storage. 1,400 meters elevation. Connected to the national grid plus an independent hydro micro-turbine. 45 minutes from Chur.",
    buildNote:"Switzerland has the world's most developed civil defense infrastructure and a mandatory underground shelter law. It has the highest political neutrality score in the world.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$850,000",
    safetyScore:{ nuclearDistance:88, disasterRisk:92, populationDensity:94, politicalStability:99 },
    imageSlug:"rea-switzerland-graubunden",
    externalUrl:"https://www.immoscout24.ch/en/real-estate/buy/region-graubuenden",
  },
  {
    id:"rea-iceland-westfjords", sku:"REA-003",
    name:"Geothermal Homestead — Westfjords",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:94,
    tier:"T2", priceUsd:28000000, priceUsdc:280000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Iceland — Westfjords",
    spec:"8-hectare coastal fjord property with geothermal heating (no fuel cost ever). River access for fresh water and a micro-hydro generator. Arctic growing season viable with a greenhouse. Ferry-only access provides natural isolation.",
    buildNote:"Iceland has zero nuclear targets. Geothermal energy eliminates all heating and energy dependency. Total national population is under 340,000. Iceland has ranked #1 on the Global Peace Index for 15 consecutive years.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$280,000",
    safetyScore:{ nuclearDistance:99, disasterRisk:86, populationDensity:99, politicalStability:98 },
    imageSlug:"rea-iceland-westfjords",
    externalUrl:"https://www.mbl.is/fasteignir/",
  },
  {
    id:"rea-uruguay-rivera", sku:"REA-004",
    name:"Highland Estancia — Rivera",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:92,
    tier:"T2", priceUsd:18000000, priceUsdc:180000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Uruguay — Rivera highlands",
    spec:"120-hectare working cattle farm with an artesian bore well and dam. Off-grid solar array already installed. 2,200 meters from the Brazilian border. Permaculture food production zones established.",
    buildNote:"Uruguay is ranked the most stable democracy in South America, with low corruption and no history of military aggression. It is in the Southern Hemisphere, outside the primary zones of any nuclear exchange scenario.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$180,000",
    safetyScore:{ nuclearDistance:94, disasterRisk:91, populationDensity:96, politicalStability:88 },
    imageSlug:"rea-uruguay-rivera",
    externalUrl:"https://www.infocasas.com.uy/",
  },
  {
    id:"rea-portugal-alentejo", sku:"REA-005",
    name:"Olive & Cork Farm — Alentejo",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:91,
    tier:"T2", priceUsd:22000000, priceUsdc:220000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Portugal — Alentejo",
    spec:"25-hectare mixed farm with 400-year-old cork oak trees that generate harvest income. Bore well and river water rights. Stone farmhouse. 1.5 hours from Lisbon airport. Solar panel infrastructure ready to install.",
    buildNote:"Portugal is a NATO member but has no nuclear weapons and a low strategic threat profile. EU residency is available through the Non-Habitual Resident (NHR) tax program. The Alentejo interior has very low population density and strong agricultural self-sufficiency.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$220,000",
    safetyScore:{ nuclearDistance:86, disasterRisk:88, populationDensity:93, politicalStability:90 },
    imageSlug:"rea-portugal-alentejo",
    externalUrl:"https://www.idealista.pt/comprar-casas/alentejo/",
  },
  {
    id:"rea-finland-lapland", sku:"REA-006",
    name:"Wilderness Lodge — Lapland Interior",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:90,
    tier:"T2", priceUsd:19000000, priceUsdc:190000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Finland — Lapland interior",
    spec:"12-hectare boreal forest property with lake frontage providing fresh water. Log construction. Wood stove plus solar hybrid power. 60 km from the nearest town. Reindeer grazing rights included.",
    buildNote:"Finland ranks in the top 5 on the Global Peace Index. Remote Lapland has roughly 2 people per km². Finland is NATO-aligned but has no strategic targets. Lake water is accessible year-round, including through ice drilling in winter.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$190,000",
    safetyScore:{ nuclearDistance:82, disasterRisk:93, populationDensity:99, politicalStability:94 },
    imageSlug:"rea-finland-lapland",
    externalUrl:"https://www.oikotie.fi/en/buying/",
  },
  {
    id:"rea-australia-tasmania", sku:"REA-007",
    name:"Orchard Retreat — Tasmania",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:86,
    tier:"T2", priceUsd:29000000, priceUsdc:290000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Australia — Tasmania",
    spec:"18-hectare fruit orchard with 150,000-liter rainwater storage capacity. 3-bedroom stone farmhouse. Standalone solar and battery power system. 40 minutes from Hobart airport. Island state geography provides natural quarantine.",
    buildNote:"Tasmania's island geography naturally separates it from mainland disruption events. Australia ranks in the Global Peace Index top 10. Low seismic risk. Temperate climate with 1,200 mm of annual rainfall.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$290,000",
    safetyScore:{ nuclearDistance:91, disasterRisk:85, populationDensity:95, politicalStability:87 },
    imageSlug:"rea-australia-tasmania",
    externalUrl:"https://www.realestate.com.au/buy/in-tasmania/",
  },
  {
    id:"rea-canada-bc-interior", sku:"REA-008",
    name:"Ranchland — British Columbia Interior",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:88,
    tier:"T2", priceUsd:32000000, priceUsdc:320000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Canada — British Columbia interior",
    spec:"80-hectare mixed ranch with creek water rights. Detached workshop and solar panel array. Timber harvesting generates income. 2 hours from Kamloops. Outside flood zones. Deer and elk hunting access on property.",
    buildNote:"The British Columbia interior has vast wilderness acting as a buffer from population centers. Canada ranks in the Global Peace Index top 10. The Okanagan/Thompson region has minimal seismic risk and reliable snowmelt water supply.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$320,000",
    safetyScore:{ nuclearDistance:78, disasterRisk:86, populationDensity:97, politicalStability:92 },
    imageSlug:"rea-canada-bc-interior",
    externalUrl:"https://www.realtor.ca/map#view=list&Sort=6-D&GeoName=British%20Columbia",
  },
  {
    id:"rea-norway-innlandet", sku:"REA-009",
    name:"Mountain Farm — Innlandet",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:87,
    tier:"T2", priceUsd:28000000, priceUsdc:280000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Norway — Innlandet",
    spec:"30-hectare highland farm with a small hydroelectric stream generating 2 kW of power. Timber barn and main house. Root cellar for cold storage. 90 minutes from Oslo. Elk and trout on the property.",
    buildNote:"Norway ranks in the Global Peace Index top 5. Innlandet county has sparse population, mountain terrain, and the micro-hydro stream eliminates any dependency on the power grid. Norwegian residency is available through investment.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$280,000",
    safetyScore:{ nuclearDistance:80, disasterRisk:90, populationDensity:96, politicalStability:95 },
    imageSlug:"rea-norway-innlandet",
    externalUrl:"https://www.finn.no/eiendom/til-salgs/",
  },
  {
    id:"rea-costa-rica-guanacaste", sku:"REA-010",
    name:"Highlands Finca — Guanacaste",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:85,
    tier:"T2", priceUsd:15000000, priceUsdc:150000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Costa Rica — Guanacaste highlands",
    spec:"12-hectare tropical farm with a natural spring water source. 2-bedroom house and guest cabin. Solar panels installed. 500+ meter elevation (above the malaria zone). 45 minutes from Liberia airport.",
    buildNote:"Costa Rica has had no standing army since 1948 and ranks in the Global Peace Index top 40. The Guanacaste highlands have low seismic activity, abundant water, and a sub-tropical growing season year-round.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$150,000",
    safetyScore:{ nuclearDistance:95, disasterRisk:76, populationDensity:88, politicalStability:84 },
    imageSlug:"rea-costa-rica-guanacaste",
    externalUrl:"https://www.century21cr.com/",
  },
  {
    id:"rea-chile-patagonia", sku:"REA-011",
    name:"Estancia — Los Lagos Patagonia",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:12000000, priceUsdc:120000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Chile — Patagonia (Los Lagos)",
    spec:"200-hectare Patagonian farm with river frontage. Working sheep and cattle operation already running. Diesel generator plus solar hybrid power. Almost zero light pollution. 2 hours from Puerto Montt.",
    buildNote:"Chilean Patagonia is extremely remote — fewer than 1 person per km² — with no strategic military value. It is in the Southern Hemisphere, outside the primary corridors of any nuclear exchange. Water source is glacier-fed river.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$120,000",
    safetyScore:{ nuclearDistance:96, disasterRisk:72, populationDensity:99, politicalStability:78 },
    imageSlug:"rea-chile-patagonia",
    externalUrl:"https://www.portalinmobiliario.com/",
  },
  {
    id:"rea-panama-boquete", sku:"REA-012",
    name:"Coffee Farm — Chiriquí (Boquete)",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:82,
    tier:"T2", priceUsd:13000000, priceUsdc:130000, highTicket:true, inStock:true,
    criticalFlag:false,
    location:"Panama — Chiriquí highlands (Boquete)",
    spec:"5-hectare highland coffee farm with a natural spring water source. 1,200-meter elevation keeps the climate cool and malaria-free. 2-bedroom farmhouse. Grid-connected plus solar backup. 30 minutes from David city. Economy uses US dollars — no currency risk.",
    buildNote:"Boquete has a well-established international community, strong infrastructure, and a USD-based economy. Panama's Friendly Nations Visa program makes residency straightforward. The highland elevation eliminates tropical disease risk.",
    listingNote:"Why this Ark node works",
    priceDisplay:"$130,000",
    safetyScore:{ nuclearDistance:93, disasterRisk:74, populationDensity:85, politicalStability:80 },
    imageSlug:"rea-panama-boquete",
    externalUrl:"https://www.boqueterealty.com/",
  },
  ...REA_EXTENDED,
];

// ── Helpers ──────────────────────────────────────────────────────────────

export function getProductById(id: string): Product | undefined {
  return CATALOG.find((p) => p.id === id);
}

export function getProductsBySku(skus: string[]): Product[] {
  return CATALOG.filter((p) => skus.includes(p.sku));
}

export function getProductsByCategory(cat: ProductCategory): Product[] {
  return CATALOG.filter((p) => p.category === cat);
}

export function getHighTicketProducts(): Product[] {
  return CATALOG.filter((p) => p.highTicket && p.inStock);
}

export function getCriticalProducts(): Product[] {
  return CATALOG.filter((p) => p.criticalFlag && p.inStock);
}

// Catalog stats for Server Component render
export const CATALOG_STATS = {
  total:       CATALOG.length,
  gradeA:      CATALOG.filter((p) => p.grade === "A").length,
  gradeB:      CATALOG.filter((p) => p.grade === "B").length,
  critical:    CATALOG.filter((p) => p.criticalFlag).length,
  highTicket:  CATALOG.filter((p) => p.highTicket).length,
  categories:  [...new Set(CATALOG.map((p) => p.category))].length,
} as const;
