// lib/provisioner/rea-extended.ts
// Extended real estate Ark nodes — global coverage
// All entries link to the best real estate search site for that country.
// safetyScore dimensions: nuclearDistance, disasterRisk, populationDensity, politicalStability (0–100)

import type { Product } from "./catalog";

export const REA_EXTENDED: Product[] = [

  // ── EUROPE — NORTHERN ─────────────────────────────────────────────────────
  {
    id:"rea-sweden-norrland", sku:"REA-013",
    name:"Forest Homestead — Norrland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:88,
    tier:"T2", priceUsd:18000000, priceUsdc:180000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Sweden — Norrland (Jämtland / Västernorrland)",
    spec:"20–80 hectare boreal forest plots. Lakes, river access, timber income. Off-grid solar viable. 1–3hr from nearest town. Dense elk population.",
    buildNote:"Sweden GPI top 10. Norrland: ~4 people/km². Vast wilderness buffer. Swedes have constitutional right to roam — supplement with owned land for food production and base camp.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:76, disasterRisk:90, populationDensity:96, politicalStability:94 },
    imageSlug:"rea-sweden-norrland",
    externalUrl:"https://www.hemnet.se/bostader?housing_form_groups%5B%5D=gård_skog_lantbruk",
  },
  {
    id:"rea-denmark-jutland", sku:"REA-014",
    name:"Rural Farm — West Jutland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:28000000, priceUsdc:280000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Denmark — Jutland (Ringkøbing-Skjern)",
    spec:"10–40 hectare mixed agricultural land. Flat terrain, reliable freshwater. Wind power viable. 1hr from Esbjerg. EU residency via ownership.",
    buildNote:"Denmark GPI top 5. West Jutland interior: sparse population, NATO but non-nuclear storage, stable democracy. EU residency pathway.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:72, disasterRisk:86, populationDensity:82, politicalStability:93 },
    imageSlug:"rea-denmark-jutland",
    externalUrl:"https://www.boligsiden.dk/landbrugsejendomme",
  },
  {
    id:"rea-ireland-connaught", sku:"REA-015",
    name:"Coastal Farm — Connaught",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:86,
    tier:"T2", priceUsd:22000000, priceUsdc:220000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Ireland — Connaught (Mayo / Galway)",
    spec:"10–50 hectare coastal or inland farm. Atlantic rainfall = water security. Stone buildings common. EU residency. 2–3hr from Dublin airport.",
    buildNote:"Ireland is not in NATO's nuclear posture, not a strike target, and benefits from Atlantic weather patterns. GPI top 15. English-speaking EU state with strong property rights.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:82, disasterRisk:84, populationDensity:88, politicalStability:89 },
    imageSlug:"rea-ireland-connaught",
    externalUrl:"https://www.daft.ie/property-for-sale/farms",
  },
  {
    id:"rea-uk-scotland", sku:"REA-016",
    name:"Highland Estate — Scotland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:35000000, priceUsdc:350000, highTicket:true, inStock:true, criticalFlag:false,
    location:"United Kingdom — Scottish Highlands (Sutherland / Caithness)",
    spec:"20–500+ hectare Highland estates available. River salmon, deer stalking, hydro micro-turbine potential. Extremely sparse population. Ferry-accessible islands also available.",
    buildNote:"Scottish Highlands: 9 people/km² in northern areas. Trident submarines at Faslane lower nuclear score but Sutherland/Caithness is >300km away. Stable democracy, strong property law.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:72, disasterRisk:86, populationDensity:92, politicalStability:84 },
    imageSlug:"rea-uk-scotland",
    externalUrl:"https://www.rightmove.co.uk/commercial-property-for-sale/find.html?locationIdentifier=REGION%5E94346",
  },

  // ── EUROPE — WESTERN ──────────────────────────────────────────────────────
  {
    id:"rea-austria-styria", sku:"REA-017",
    name:"Alpine Farm — Styria",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:85,
    tier:"T2", priceUsd:32000000, priceUsdc:320000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Austria — Styria (Murtal / Murau)",
    spec:"5–30 hectare alpine farms. Spring-fed water, timber, grazing. Log + masonry construction. Solar + wood stove viable. 2hr from Graz.",
    buildNote:"Austria is EU but not NATO nuclear host. Styrian Alps: dense forest, natural defensive terrain, strong off-grid tradition. Austria's neutrality since 1955 reduces strike profile.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:78, disasterRisk:85, populationDensity:88, politicalStability:88 },
    imageSlug:"rea-austria-styria",
    externalUrl:"https://www.willhaben.at/iad/immobilien/land-und-forstwirtschaft",
  },
  {
    id:"rea-germany-bavaria", sku:"REA-018",
    name:"Rural Farmstead — Bavaria",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:81,
    tier:"T2", priceUsd:45000000, priceUsdc:450000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Germany — Bavaria (Upper Palatinate / Lower Bavaria)",
    spec:"5–20 hectare farms with outbuildings. River access, fertile soil. Pre-1950 farmhouse common. Solar + geothermal viable. 1.5hr from Munich.",
    buildNote:"Germany NATO member — lowers nuclear score. However rural Bavaria away from airbases has low direct risk. Strong rule of law, excellent infrastructure, EU residency.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:70, disasterRisk:85, populationDensity:82, politicalStability:87 },
    imageSlug:"rea-germany-bavaria",
    externalUrl:"https://www.immoscout24.de/expose/landwirtschaft",
  },
  {
    id:"rea-france-auvergne", sku:"REA-019",
    name:"Volcanic Plateau Farm — Auvergne",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:82,
    tier:"T2", priceUsd:15000000, priceUsdc:150000, highTicket:true, inStock:true, criticalFlag:false,
    location:"France — Auvergne-Rhône-Alpes (Cantal / Haute-Loire)",
    spec:"10–80 hectare volcanic plateau farms. Spring water, cattle grazing, chestnuts. Stone farmhouses. Extremely rural. 2hr from Clermont-Ferrand.",
    buildNote:"France has nuclear arsenal (Paris is a target) but the Massif Central is ~500km from Paris and has near-zero strategic value. Among cheapest farmland in Western Europe.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:74, disasterRisk:83, populationDensity:92, politicalStability:83 },
    imageSlug:"rea-france-auvergne",
    externalUrl:"https://www.seloger.com/acheter/terrains/",
  },
  {
    id:"rea-spain-extremadura", sku:"REA-020",
    name:"Dehesa — Extremadura",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:14000000, priceUsdc:140000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Spain — Extremadura (Cáceres / Badajoz)",
    spec:"20–200 hectare dehesa (cork oak savanna). Spring water, Ibérico pigs viable, honey. Stone cortijo farmhouse. 2hr from Seville. EU Golden Visa pathway.",
    buildNote:"Extremadura: 26 people/km² — emptiest region in Spain. No nuclear targets. EU Golden Visa via property purchase (€500k+). 300+ sun days — solar excellent.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:82, disasterRisk:78, populationDensity:92, politicalStability:81 },
    imageSlug:"rea-spain-extremadura",
    externalUrl:"https://www.idealista.com/venta-fincas-rusticas/extremadura/",
  },
  {
    id:"rea-italy-abruzzo", sku:"REA-021",
    name:"Mountain Farm — Abruzzo",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Italy — Abruzzo (L'Aquila province)",
    spec:"5–30 hectare mountain farms with borgo-style stone buildings. Spring water. Wolves, wild boar. National park adjacency. Very cheap — some farms under €30k.",
    buildNote:"Abruzzo is among cheapest land in Europe. Seismic risk (L'Aquila 2009) lowers score. Very remote interior. No nuclear targets. 100km from Rome but worlds apart.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:78, disasterRisk:68, populationDensity:90, politicalStability:76 },
    imageSlug:"rea-italy-abruzzo",
    externalUrl:"https://www.immobiliare.it/vendita-terreni/l-aquila/",
  },
  {
    id:"rea-greece-epirus", sku:"REA-022",
    name:"Mountain Village Land — Epirus",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:78,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Greece — Epirus (Zagori / Tzoumerka)",
    spec:"2–20 hectare mountain plots with stone houses. River gorges. Timber, honey, livestock. Very isolated. 2hr from Ioannina. EU residency (€250k Golden Visa).",
    buildNote:"Greece GPI moderate. Epirus mountains: natural terrain barrier, no strategic value, very low population. Seismic risk is real — stone construction with proper foundation critical.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:68, populationDensity:90, politicalStability:74 },
    imageSlug:"rea-greece-epirus",
    externalUrl:"https://www.xe.gr/en/property/",
  },

  // ── EUROPE — CENTRAL & EASTERN ────────────────────────────────────────────
  {
    id:"rea-czech-bohemia", sku:"REA-023",
    name:"Forest Farm — South Bohemia",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:84,
    tier:"T2", priceUsd:16000000, priceUsdc:160000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Czech Republic — South Bohemia (Šumava / Česky Krumlov)",
    spec:"5–50 hectare mixed forest + farmland. Ponds (fish farming), timber, meadows. EU residency. 2hr from Prague. Šumava National Park border properties available.",
    buildNote:"Czech Republic not a nuclear host. No direct targets in rural south. Top-ranked democracy in Central Europe. Affordable vs Western Europe. Strong property rights.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:78, disasterRisk:88, populationDensity:84, politicalStability:85 },
    imageSlug:"rea-czech-bohemia",
    externalUrl:"https://www.sreality.cz/hledani/prodej/pozemky/",
  },
  {
    id:"rea-poland-mazury", sku:"REA-024",
    name:"Lake District Land — Mazury",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:81,
    tier:"T2", priceUsd:12000000, priceUsdc:120000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Poland — Warmia-Mazury (Great Mazurian Lakes)",
    spec:"5–100 hectare lake-adjacent farms and forest. 3,000 lakes in region. Timber, fishing, agriculture. EU residency. Warsaw 3hr by road.",
    buildNote:"Poland NATO eastern flank — nuclear score lower than ideal. However Mazury is remote from Warsaw and military installations. EU membership, strong growth, property rights secure.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:72, disasterRisk:87, populationDensity:86, politicalStability:78 },
    imageSlug:"rea-poland-mazury",
    externalUrl:"https://www.otodom.pl/pl/oferty/sprzedaz/dzialka/",
  },
  {
    id:"rea-hungary-baranya", sku:"REA-025",
    name:"Wine Country Farm — Baranya",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:81,
    tier:"T2", priceUsd:9000000, priceUsdc:90000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Hungary — Baranya county (Villány / Ormánság)",
    spec:"5–50 hectare farms with vineyards, orchards, or arable land. EU residency. 1hr from Pécs. Among cheapest farmland in the EU.",
    buildNote:"Hungary not a nuclear target. Baranya is remote from Budapest, near Croatian border. Some political concerns (Orbán) but EU membership protects property rights.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:78, disasterRisk:86, populationDensity:86, politicalStability:72 },
    imageSlug:"rea-hungary-baranya",
    externalUrl:"https://www.ingatlan.com/tanya-gazdasag-elado",
  },
  {
    id:"rea-romania-transylvania", sku:"REA-026",
    name:"Saxon Village Farm — Transylvania",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:7000000, priceUsdc:70000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Romania — Transylvania (Sibiu / Brașov county)",
    spec:"5–100 hectare farms with Saxon-era farmhouses. Pasture, forest, stream. EU residency. 1hr from Sibiu. Some of cheapest farmland in EU — €5k–€30k/hectare.",
    buildNote:"Romania EU member, NATO but no nuclear deployment. Transylvanian interior: sparse, no targets. King Charles III has restored properties here — international attention growing.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:78, disasterRisk:72, populationDensity:88, politicalStability:71 },
    imageSlug:"rea-romania-transylvania",
    externalUrl:"https://www.imobiliare.ro/vanzare-terenuri/",
  },
  {
    id:"rea-bulgaria-rhodope", sku:"REA-027",
    name:"Mountain Village — Rhodope",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:79,
    tier:"T2", priceUsd:5000000, priceUsdc:50000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Bulgaria — Rhodope Mountains (Smolyan / Kardzhali)",
    spec:"2–20 hectare mountain farms, some with springs and forest. Stone village houses available under €10k. EU residency. Very remote. 2hr from Plovdiv.",
    buildNote:"Bulgaria EU member. Rhodope mountains: <20 people/km², no military value. Cheapest EU real estate. Low political stability score offset by genuine remoteness and self-sufficiency.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:78, populationDensity:92, politicalStability:66 },
    imageSlug:"rea-bulgaria-rhodope",
    externalUrl:"https://www.imot.bg/pcgi/imot.cgi?act=11&f1=1&f2=1",
  },
  {
    id:"rea-slovenia-karst", sku:"REA-028",
    name:"Karst Farmstead — Primorska",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:18000000, priceUsdc:180000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Slovenia — Primorska (Kras / Vipava Valley)",
    spec:"2–20 hectare Karst farms with wine + olive production. Underground water cisterns. Stone architecture. EU residency. 1hr from Ljubljana.",
    buildNote:"Slovenia GPI top 15. No nuclear targets. Karst plateau: natural cave systems for storage, spring water, Mediterranean microclimate. EU member with stable democracy.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:80, populationDensity:88, politicalStability:84 },
    imageSlug:"rea-slovenia-karst",
    externalUrl:"https://www.nepremicnine.net/oglasi-prodaja/kmetijsko-zemljisce/",
  },
  {
    id:"rea-slovakia-tatras", sku:"REA-029",
    name:"Mountain Land — Slovak Tatras",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:84,
    tier:"T2", priceUsd:11000000, priceUsdc:110000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Slovakia — Prešov Region (Spišská Magura / Pieniny)",
    spec:"5–50 hectare mountain farms with timber and pasture. Spring water. EU residency. 2hr from Bratislava. Affordable vs western neighbors.",
    buildNote:"Slovakia EU and NATO but no nuclear storage. Tatra highlands: dense forest, very sparse, no targets. Strong EU rule of law protections. Good value per hectare.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:87, populationDensity:88, politicalStability:79 },
    imageSlug:"rea-slovakia-tatras",
    externalUrl:"https://www.nehnutelnosti.sk/pozemky/",
  },
  {
    id:"rea-croatia-dalmatia", sku:"REA-030",
    name:"Island Farm — Dalmatian Coast",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:20000000, priceUsdc:200000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Croatia — Dalmatia (Pelješac / Hvar inland)",
    spec:"2–20 hectare inland Mediterranean farms. Olive groves, vineyard, cistern water. Stone farmhouse. EU residency. Ferry access creates natural isolation.",
    buildNote:"Croatia EU member, NATO but no nuclear assets. Dalmatian islands: ferry-dependent isolation is a security asset. Seismic risk real — stone construction required. Strong tourism economy.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:82, disasterRisk:74, populationDensity:88, politicalStability:76 },
    imageSlug:"rea-croatia-dalmatia",
    externalUrl:"https://www.njuskalo.hr/prodaja-zemljista",
  },
  {
    id:"rea-estonia-saaremaa", sku:"REA-031",
    name:"Island Farm — Saaremaa",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Estonia — Saaremaa island",
    spec:"5–100 hectare island farms. Juniper heath, forest, coastal access. Ferry from mainland. EU residency. Very low density — 16 people/km².",
    buildNote:"Estonia EU + NATO, but Saaremaa is an island — ferry creates tactical separation. EU e-Residency available. Russian proximity is the primary risk. Strong digital infrastructure.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:65, disasterRisk:90, populationDensity:92, politicalStability:84 },
    imageSlug:"rea-estonia-saaremaa",
    externalUrl:"https://www.kv.ee/search?deal_type=1&object_type%5B%5D=4",
  },
  {
    id:"rea-latvia-latgale", sku:"REA-032",
    name:"Lake Farm — Latgale",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:7000000, priceUsdc:70000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Latvia — Latgale (Rēzekne / Daugavpils)",
    spec:"5–100 hectare lake district farms. 3,000 lakes. Timber, fishing, agriculture. EU residency. 3hr from Riga. Cheapest EU land prices.",
    buildNote:"Latvia NATO, borders Russia (risk). Latgale is eastern — contradictory but cheapest EU farmland. For the risk-tolerant buyer seeking maximum land per dollar within EU law.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:63, disasterRisk:90, populationDensity:92, politicalStability:78 },
    imageSlug:"rea-latvia-latgale",
    externalUrl:"https://www.ss.lv/lv/real-estate/land-for-sale/",
  },
  {
    id:"rea-lithuania-dzukija", sku:"REA-033",
    name:"Forest Land — Dzūkija",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Lithuania — Dzūkija (Varėna / Lazdijai)",
    spec:"5–50 hectare pine forest + mushroom land. Sandy soil, rivers, wild boar. EU residency. 2hr from Vilnius. Very affordable vs EU average.",
    buildNote:"Lithuania NATO (Suwalki gap risk). Dzūkija national park region: near-zero population, no targets. EU membership protects property rights. Best value in Baltic for forest land.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:62, disasterRisk:90, populationDensity:90, politicalStability:79 },
    imageSlug:"rea-lithuania-dzukija",
    externalUrl:"https://www.aruodas.lt/zemes-sklypai-parduodami/",
  },
  {
    id:"rea-serbia-sumadija", sku:"REA-034",
    name:"River Valley Farm — Šumadija",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:7000000, priceUsdc:70000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Serbia — Šumadija (Rudnik Mountain)",
    spec:"5–50 hectare farms with orchards, plum for rakija, rivers. Stone homesteads. No EU requirement for purchase — foreigners can buy. 1.5hr from Belgrade.",
    buildNote:"Serbia not NATO, not EU — foreigners buy freely with no restrictions. No nuclear posture. Rural Šumadija: self-sufficient agricultural tradition, spring water, dense forest.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:82, disasterRisk:80, populationDensity:86, politicalStability:62 },
    imageSlug:"rea-serbia-sumadija",
    externalUrl:"https://www.halooglasi.com/nekretnine/prodaja-kuca-i-placeva",
  },
  {
    id:"rea-montenegro-highlands", sku:"REA-035",
    name:"Mountain Land — Montenegro Interior",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Montenegro — Durmitor / Pivska plateau",
    spec:"5–50 hectare highland land at 1,200–1,600m elevation. River canyons, pine forest, glacial lakes. Very cheap. No EU residency requirement for purchase.",
    buildNote:"Montenegro NATO member but no nuclear assets. Durmitor: one of Europe's most remote mountain plateaus. Foreigners can buy freely. Growing expat community. EU candidate.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:82, disasterRisk:78, populationDensity:92, politicalStability:70 },
    imageSlug:"rea-montenegro-highlands",
    externalUrl:"https://www.montenegroproperty.com/",
  },

  // ── AMERICAS ──────────────────────────────────────────────────────────────
  {
    id:"rea-usa-montana", sku:"REA-036",
    name:"Ranch Land — Montana / Wyoming",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:40000000, priceUsdc:400000, highTicket:true, inStock:true, criticalFlag:false,
    location:"USA — Montana / Wyoming (Big Timber / Cody / Laramie region)",
    spec:"40–4,000 acre ranches. Creek or well water. Off-grid solar viable. Hunting, cattle, timber. Strong property rights. 4–6hr from major cities.",
    buildNote:"Montana and Wyoming have ICBM silos (Malmstrom AFB area is a target zone) — avoid within 100km of known silo fields. South-central Montana and Wyoming basin are outside primary zones. No state income tax (WY).",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:62, disasterRisk:80, populationDensity:95, politicalStability:82 },
    imageSlug:"rea-usa-montana",
    externalUrl:"https://www.zillow.com/homes/for_sale/land_type/",
  },
  {
    id:"rea-mexico-oaxaca", sku:"REA-037",
    name:"Highland Farmland — Oaxaca",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:73,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Mexico — Oaxaca (Sierra Juárez highlands)",
    spec:"5–50 hectare highland farms at 1,500–2,500m elevation. Spring water, coffee, corn. Cool climate. Traditional communities. 2hr from Oaxaca city.",
    buildNote:"Mexico has security concerns in lowlands — highland Oaxaca is distinctly safer. No nuclear targets. Southern hemisphere adjacency. Foreigners may purchase through bank trust (fideicomiso). USD readily accepted.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:84, disasterRisk:68, populationDensity:86, politicalStability:54 },
    imageSlug:"rea-mexico-oaxaca",
    externalUrl:"https://www.inmuebles24.com/terrenos-en-venta-en-oaxaca.html",
  },
  {
    id:"rea-belize-cayo", sku:"REA-038",
    name:"Jungle Farm — Cayo District",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:81,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Belize — Cayo District (San Ignacio / Mountain Pine Ridge)",
    spec:"5–50 hectare jungle and pine ridge farms. River frontage, spring water. Off-grid solar. English-speaking. QRP residency available. 1hr from Guatemala border.",
    buildNote:"Belize English-speaking, USD-pegged, no military threat profile. QRP (Qualified Retired Persons) residency is easy. Very affordable jungle land. No property capital gains tax.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:92, disasterRisk:68, populationDensity:92, politicalStability:72 },
    imageSlug:"rea-belize-cayo",
    externalUrl:"https://www.belizerealestate.com/",
  },
  {
    id:"rea-brazil-minas", sku:"REA-039",
    name:"Cerrado Farm — Minas Gerais",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:15000000, priceUsdc:150000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Brazil — Minas Gerais (Serra da Canastra / Triângulo)",
    spec:"20–500 hectare cerrado farms. Deep aquifer water, tropical fruit, soy rotation viable. Very cheap per hectare. 4hr from Belo Horizonte.",
    buildNote:"Brazil southern hemisphere — outside primary nuclear exchange corridors. Interior Minas Gerais: no targets, warm climate year-round, abundant groundwater, minimal seismic risk.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:76, populationDensity:88, politicalStability:62 },
    imageSlug:"rea-brazil-minas",
    externalUrl:"https://www.vivareal.com.br/venda/rural/",
  },
  {
    id:"rea-argentina-mendoza", sku:"REA-040",
    name:"Wine & Farmland — Mendoza Foothills",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:79,
    tier:"T2", priceUsd:12000000, priceUsdc:120000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Argentina — Mendoza (San Rafael / Malargüe)",
    spec:"10–500 hectare foothill farms and vineyards. Snowmelt irrigation channels (acequia). Wine, olives, goats. 3hr from Mendoza city. Very cheap in USD terms.",
    buildNote:"Southern hemisphere advantage. Mendoza foothills: snowmelt water security, fertile alluvial soil, no nuclear value. Argentina's currency instability means USD buyers get extreme value. Seismic risk moderate in west.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:72, populationDensity:90, politicalStability:58 },
    imageSlug:"rea-argentina-mendoza",
    externalUrl:"https://www.zonaprop.com.ar/campos-y-estancias-venta.html",
  },
  {
    id:"rea-colombia-coffee", sku:"REA-041",
    name:"Coffee Finca — Eje Cafetero",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:14000000, priceUsdc:140000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Colombia — Eje Cafetero (Risaralda / Quindío)",
    spec:"5–20 hectare coffee fincas at 1,400–2,000m. Spring water, year-round production. Bamboo-guadua construction. 1hr from Medellín. Spring climate year-round.",
    buildNote:"Colombia improving stability. Coffee region is the safest and most developed area. Southern hemisphere. 1,500m elevation = no tropical disease. No nuclear targets anywhere in Colombia.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:70, populationDensity:80, politicalStability:60 },
    imageSlug:"rea-colombia-coffee",
    externalUrl:"https://www.metrocuadrado.com/fincas/",
  },
  {
    id:"rea-peru-andes", sku:"REA-042",
    name:"Andean Farmland — Sacred Valley",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:75,
    tier:"T2", priceUsd:9000000, priceUsdc:90000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Peru — Cusco Region (Sacred Valley / Urubamba)",
    spec:"2–20 hectare Andean farms at 2,800–3,500m elevation. Quinoa, potato, livestock. Spring water. Indigenous land rights complex — use licensed agent. 1hr from Cusco.",
    buildNote:"Peru southern hemisphere. Sacred Valley: volcanic soil, year-round growing season, no nuclear targets. Altitude eliminates most tropical disease. Complex land titles — due diligence essential.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:64, populationDensity:86, politicalStability:54 },
    imageSlug:"rea-peru-andes",
    externalUrl:"https://urbania.pe/buscar/terrenos-en-venta",
  },
  {
    id:"rea-ecuador-andes", sku:"REA-043",
    name:"Highland Farm — Ecuadorian Andes",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Ecuador — Cotopaxi / Tungurahua (Latacunga / Riobamba valley)",
    spec:"5–50 hectare Andean valley farms. Volcanic soil extremely fertile. Rose, broccoli, dairy. USD economy (no currency risk). Spring water. 2hr from Quito.",
    buildNote:"Ecuador is USD economy — no devaluation risk. Southern hemisphere, no nuclear targets. Volcanic fertility is the best in South America. Volcanic hazard (Cotopaxi) is real — choose location carefully.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:66, populationDensity:84, politicalStability:60 },
    imageSlug:"rea-ecuador-andes",
    externalUrl:"https://www.plusvalia.com/terrenos-en-venta.html",
  },
  {
    id:"rea-paraguay-interior", sku:"REA-044",
    name:"Agricultural Land — Eastern Paraguay",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:82,
    tier:"T2", priceUsd:6000000, priceUsdc:60000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Paraguay — Eastern Region (Itapúa / Caazapá)",
    spec:"20–500 hectare flatland farms. Deep black soil. Soy, cattle, timber. Abundant surface water. Among cheapest farmland in South America. Easy residency.",
    buildNote:"Paraguay southern hemisphere, zero nuclear targets. Eastern Paraguay: Guaraní aquifer = unlimited groundwater. 1-year residency to citizenship. No capital gains tax on property. Very low cost of living.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:78, populationDensity:88, politicalStability:64 },
    imageSlug:"rea-paraguay-interior",
    externalUrl:"https://www.clasificados.com.py/inmuebles/campos",
  },
  {
    id:"rea-bolivia-beni", sku:"REA-045",
    name:"Amazon Frontier — Beni",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:79,
    tier:"T2", priceUsd:5000000, priceUsdc:50000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Bolivia — Beni department (Santa Cruz border region)",
    spec:"100–5,000 hectare Amazon frontier land. Very cheap per hectare. River access. Cattle, Brazil nuts, timber. 4WD essential. Growing agricultural frontier.",
    buildNote:"Bolivia southern hemisphere, zero nuclear threat. Amazon interior: extreme remoteness. Political instability is real risk. USD stable vs boliviano. Best for extreme-isolation buyers with budget constraints.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:76, populationDensity:92, politicalStability:52 },
    imageSlug:"rea-bolivia-beni",
    externalUrl:"https://www.properati.com.bo/terrenos_en_venta",
  },

  // ── ASIA-PACIFIC ──────────────────────────────────────────────────────────
  {
    id:"rea-japan-hokkaido", sku:"REA-046",
    name:"Forest Farm — Hokkaido",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:75,
    tier:"T2", priceUsd:20000000, priceUsdc:200000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Japan — Hokkaido (Dōtō / Hidaka)",
    spec:"5–50 hectare Hokkaido farms. Dairy, potato, beet. Very cheap land — some plots under ¥500k. Freshwater rivers. Cool climate. 2–4hr from Sapporo.",
    buildNote:"Japan US alliance partner (potential nuclear target). However Hokkaido's interior is >1,000km from Tokyo/Yokohama. Extremely high seismic + tsunami risk on coasts — choose elevated inland. Strong property rights.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:72, disasterRisk:58, populationDensity:84, politicalStability:86 },
    imageSlug:"rea-japan-hokkaido",
    externalUrl:"https://www.suumo.jp/tochi/hokkaido/",
  },
  {
    id:"rea-thailand-chiangmai", sku:"REA-047",
    name:"Mountain Farm — Chiang Rai",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Thailand — Chiang Rai (Doi Mae Salong highlands)",
    spec:"2–20 hectare highland farms at 800–1,200m. Tea, fruit, coffee. Spring water. Cool dry season. Thai lease or company structure required for foreigners. 1hr from Chiang Rai.",
    buildNote:"Thailand no nuclear targets. Golden Triangle border area: remote, cooler climate, flooding rare. Foreigners lease land (30+30+30 yr) or use Thai company structure — consult lawyer. Low cost of living.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:90, disasterRisk:74, populationDensity:84, politicalStability:62 },
    imageSlug:"rea-thailand-chiangmai",
    externalUrl:"https://www.ddproperty.com/en/property-for-sale/land",
  },
  {
    id:"rea-malaysia-sabah", sku:"REA-048",
    name:"Jungle Smallholding — Sabah",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:82,
    tier:"T2", priceUsd:12000000, priceUsdc:120000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Malaysia — Sabah (Interior Division / Tambunan)",
    spec:"5–100 hectare Borneo interior farms. River access, fruit orchards, palm oil. Malaysia My Second Home (MM2H) visa available. 2–4hr from Kota Kinabalu.",
    buildNote:"Sabah Borneo: zero nuclear targets, dense jungle buffer, equatorial freshwater abundance, no cyclone belt. Malaysia My Second Home visa grants 10-year renewable residency. English widely spoken.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:78, populationDensity:86, politicalStability:72 },
    imageSlug:"rea-malaysia-sabah",
    externalUrl:"https://www.propertyguru.com.my/property-for-sale/land",
  },
  {
    id:"rea-cambodia-kampot", sku:"REA-049",
    name:"River Farm — Kampot Province",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:76,
    tier:"T2", priceUsd:6000000, priceUsdc:60000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Cambodia — Kampot (Bokor highlands / Tek Chhou river valley)",
    spec:"2–20 hectare river farms. Pepper, durian, rice. Mountain spring water. Very cheap. USD economy. 30-year lease or company structure for foreigners. 3hr from Phnom Penh.",
    buildNote:"Cambodia USD economy, no currency risk. Kampot: coolest microclimate in Cambodia, spring water, no flood risk at elevation. Very low land prices. Political risk (Hun Manet regime) is real but property remains stable.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:92, disasterRisk:72, populationDensity:86, politicalStability:54 },
    imageSlug:"rea-cambodia-kampot",
    externalUrl:"https://www.realestate.com.kh/buy/land/",
  },
  {
    id:"rea-vietnam-dalat", sku:"REA-050",
    name:"Highlands Farm — Đà Lạt",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:74,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Vietnam — Lâm Đồng Province (Đà Lạt / Di Linh highlands)",
    spec:"2–20 hectare highland farms at 1,500m. Coffee, strawberry, artichoke, cut flowers. Spring water. Cool climate. 1hr from Da Lat city. 50-year lease available.",
    buildNote:"Vietnam no nuclear targets. Da Lat highlands: France-built hill station, cool spring climate, no malaria, very cheap land. Foreigners use 50-year lease + 50-year extension. One of Asia's most diverse agricultural climates.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:90, disasterRisk:70, populationDensity:80, politicalStability:58 },
    imageSlug:"rea-vietnam-dalat",
    externalUrl:"https://batdongsan.com.vn/ban-dat",
  },
  {
    id:"rea-philippines-palawan", sku:"REA-051",
    name:"Island Land — Palawan",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:70,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Philippines — Palawan (Puerto Princesa / El Nido hinterland)",
    spec:"1–10 hectare coastal or interior land. Freshwater rivers, limestone karst, coconut. Foreigners lease only (25+25 yr or corporation). Extremely remote. Ferry access.",
    buildNote:"Palawan is the most biodiverse island in the Philippines. Zero nuclear targets. English-speaking. Typhoon risk lower here than Visayas (check specific location). Earthquake risk moderate.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:92, disasterRisk:54, populationDensity:76, politicalStability:62 },
    imageSlug:"rea-philippines-palawan",
    externalUrl:"https://www.lamudi.com.ph/land/for-sale/",
  },
  {
    id:"rea-indonesia-lombok", sku:"REA-052",
    name:"Hillside Land — Lombok",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:74,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Indonesia — West Nusa Tenggara (Lombok interior / Senaru)",
    spec:"1–10 hectare volcanic hillside land. Spring water, rice terraces, cacao. HGBU foreigner title available. 1hr from Lombok Airport. Lower density than Bali.",
    buildNote:"Lombok less developed than Bali — lower density, more affordable. Zero nuclear targets. Volcanic soil extremely fertile. Seismic risk real (2018 quake M6.9) — build with earthquake-resistant design.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:58, populationDensity:78, politicalStability:68 },
    imageSlug:"rea-indonesia-lombok",
    externalUrl:"https://www.rumah123.com/jual/tanah/",
  },

  // ── CAUCASUS & CENTRAL ASIA ───────────────────────────────────────────────
  {
    id:"rea-georgia-kakheti", sku:"REA-053",
    name:"Wine Country Farm — Kakheti",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:78,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Georgia — Kakheti (Alazani Valley)",
    spec:"2–30 hectare wine-country farms. Vine, walnut, hazelnut. Artesian well. Foreigners buy freely. 2hr from Tbilisi. Small winery operations common.",
    buildNote:"Georgia: foreigners may purchase freely with no restrictions. 1% flat income tax for small agriculture. Zero nuclear targets. Russia conflict (2008, 2022 ongoing) is the primary risk — Kakheti is far from conflict zones.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:84, disasterRisk:76, populationDensity:88, politicalStability:64 },
    imageSlug:"rea-georgia-kakheti",
    externalUrl:"https://www.myhome.ge/en/s/land",
  },
  {
    id:"rea-armenia-tavush", sku:"REA-054",
    name:"Mountain Farm — Tavush",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:74,
    tier:"T2", priceUsd:5000000, priceUsdc:50000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Armenia — Tavush (Dilijan / Ijevan)",
    spec:"2–20 hectare mountain farms. Hazelnut, apricot, grape, honey. Spring water from volcanic highlands. Foreigners buy freely. 1.5hr from Yerevan.",
    buildNote:"Armenia zero nuclear targets. Seismic risk real (1988 Spitak earthquake). Azerbaijan border conflict ongoing — Tavush is on the northern border, not NK conflict zone. Extremely cheap land.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:86, disasterRisk:66, populationDensity:84, politicalStability:62 },
    imageSlug:"rea-armenia-tavush",
    externalUrl:"https://www.list.am/en/category/6",
  },
  {
    id:"rea-kyrgyzstan-issykkul", sku:"REA-055",
    name:"Alpine Farmland — Issyk-Kul",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:75,
    tier:"T2", priceUsd:4000000, priceUsdc:40000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Kyrgyzstan — Issyk-Kul Oblast",
    spec:"5–100 hectare alpine farms around the world's 2nd largest mountain lake. Livestock, hay, orchard. Freshwater lake at 1,600m. Foreigners can lease; citizens own.",
    buildNote:"Kyrgyzstan zero nuclear targets. Issyk-Kul: natural salt lake that never freezes, surrounded by Tian Shan peaks to 7,000m. Extremely remote. Very cheap. Political coups have occurred but land rights stable.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:86, disasterRisk:70, populationDensity:90, politicalStability:52 },
    imageSlug:"rea-kyrgyzstan-issykkul",
    externalUrl:"https://www.stroi.kg/en/",
  },

  // ── MIDDLE EAST ──────────────────────────────────────────────────────────
  {
    id:"rea-oman-interior", sku:"REA-056",
    name:"Agricultural Land — Oman Interior",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:81,
    tier:"T2", priceUsd:18000000, priceUsdc:180000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Oman — Al Dakhiliyah (Nizwa / Jabal Al Akhdar)",
    spec:"2–20 hectare interior farms. Falaj (ancient gravity irrigation) systems. Dates, pomegranate, rose water. 1,500–2,000m elevation mountain areas available. 2hr from Muscat.",
    buildNote:"Oman officially neutral — never engaged in regional conflicts since 1976. Al Akhdar mountain: 2,000m elevation, cool climate, spring irrigation. Zero nuclear targets. Stable sultanate with proven property rights for foreigners (Integrated Tourism Complexes).",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:86, disasterRisk:76, populationDensity:92, politicalStability:74 },
    imageSlug:"rea-oman-interior",
    externalUrl:"https://www.propertyfinder.om/en/buy/land-plots",
  },
  {
    id:"rea-jordan-aqaba", sku:"REA-057",
    name:"Desert Farm — Wadi Rum Region",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:15000000, priceUsdc:150000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Jordan — Ma'an Governorate (Wadi Rum / Aqaba highlands)",
    spec:"5–50 hectare desert valley farms. Wadi groundwater, date palm, olive. Jordan residency via investment available. 1hr from Aqaba airport.",
    buildNote:"Jordan diplomatically neutral — Camp David-aligned but not involved in active conflicts. Wadi Rum: zero population, no targets. Jordan River valley water access. Stable monarchy with strong property law. No capital gains tax.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:82, populationDensity:88, politicalStability:64 },
    imageSlug:"rea-jordan-aqaba",
    externalUrl:"https://www.property.com.jo/en/",
  },

  // ── AFRICA ────────────────────────────────────────────────────────────────
  {
    id:"rea-namibia-central", sku:"REA-058",
    name:"Bush Farm — Central Namibia",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:87,
    tier:"T2", priceUsd:20000000, priceUsdc:200000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Namibia — Khomas / Otjozondjupa (Gobabis / Okahandja)",
    spec:"500–10,000 hectare bush farms. Borehole water, cattle, game. Solar power viable. Very sparse — 3 people/km² nationally. 1–2hr from Windhoek.",
    buildNote:"Namibia one of Africa's most stable democracies. GPI top 50 Africa. Zero nuclear profile. 3 people/km² makes it one of the least dense countries on Earth. Southern hemisphere, far from all conflict zones.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:80, populationDensity:98, politicalStability:74 },
    imageSlug:"rea-namibia-central",
    externalUrl:"https://www.private-property.com.na/namibia/farms",
  },
  {
    id:"rea-botswana-rural", sku:"REA-059",
    name:"Wildlife Farm — Central Botswana",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:86,
    tier:"T2", priceUsd:18000000, priceUsdc:180000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Botswana — Central District (Serowe / Palapye)",
    spec:"500–5,000 hectare farms and wildlife ranches. Borehole water. Cattle or game (photographic / hunting). Solar viable. 3hr from Gaborone.",
    buildNote:"Botswana consistently Africa's best governance score (Ibrahim Index). Diamond wealth enables stable institutions. Very sparse. Southern hemisphere. No nuclear profile. Strong land title system.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:95, disasterRisk:80, populationDensity:96, politicalStability:76 },
    imageSlug:"rea-botswana-rural",
    externalUrl:"https://www.homenet.co.bw/listings/farms",
  },
  {
    id:"rea-zambia-southern", sku:"REA-060",
    name:"River Farm — Southern Zambia",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:84,
    tier:"T2", priceUsd:12000000, priceUsdc:120000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Zambia — Southern Province (Choma / Monze)",
    spec:"50–500 hectare plateau farms. Deep black soil. Zambia's food basket. Borehole + river water. Maize, soy, cattle. Foreigners lease 99 years. 3hr from Lusaka.",
    buildNote:"Zambia peaceful — zero military conflicts since independence. Southern highlands: 1,200m elevation, no malaria. Zero nuclear profile. 99-year lease gives generational security. Agriculture highly productive.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:82, populationDensity:92, politicalStability:66 },
    imageSlug:"rea-zambia-southern",
    externalUrl:"https://www.lamudi.co.zm/land/",
  },
  {
    id:"rea-tanzania-highland", sku:"REA-061",
    name:"Coffee Farm — Southern Highlands",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:82,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Tanzania — Mbeya Region (Mbozi / Rungwe highlands)",
    spec:"5–100 hectare highland farms at 1,500–2,500m. Coffee, tea, avocado. Volcanic soil, spring water, zero malaria. 99-year occupancy rights for foreigners.",
    buildNote:"Tanzania has been conflict-free since independence. Southern highlands: coolest climate in East Africa, fertile volcanic soil, no nuclear profile. 99-year Right of Occupancy lease gives security.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:78, populationDensity:88, politicalStability:66 },
    imageSlug:"rea-tanzania-highland",
    externalUrl:"https://www.tanzaniaproperties.co.tz/",
  },
  {
    id:"rea-kenya-laikipia", sku:"REA-062",
    name:"Ranch Land — Laikipia Plateau",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:79,
    tier:"T2", priceUsd:25000000, priceUsdc:250000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Kenya — Laikipia County (Nanyuki / Rumuruti)",
    spec:"100–10,000 hectare cattle or wildlife ranches at 1,700–2,500m elevation. Equatorial climate moderated by altitude. Borehole water. Year-round cool.",
    buildNote:"Laikipia plateau is Kenya's most productive and stable ranching region. Zero nuclear targets. 1,800m elevation eliminates malaria. Foreigners own freehold via company structure. Strong rule of law in property.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:95, disasterRisk:76, populationDensity:84, politicalStability:62 },
    imageSlug:"rea-kenya-laikipia",
    externalUrl:"https://www.buyrentkenya.com/land-for-sale",
  },
  {
    id:"rea-morocco-atlas", sku:"REA-063",
    name:"Atlas Mountain Farm — Morocco",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:77,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Morocco — High Atlas (Ouarzazate / Azilal)",
    spec:"5–50 hectare mountain farms. Irrigated terraces, almond, olive, saffron. Spring water from Atlas snowmelt. Foreigners buy freely. 3hr from Marrakech.",
    buildNote:"Morocco Africa's most stable monarchy. Atlas interior: zero nuclear profile, cool mountain climate, ancient irrigation systems. Foreigners purchase freely with title deed (Titre Foncier). Tourism income potential.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:88, disasterRisk:72, populationDensity:84, politicalStability:66 },
    imageSlug:"rea-morocco-atlas",
    externalUrl:"https://www.mubawab.ma/fr/ct/maroc/terrains-a-vendre",
  },
  {
    id:"rea-rwanda-kivu", sku:"REA-064",
    name:"Hill Farm — Lake Kivu Region",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:80,
    tier:"T2", priceUsd:8000000, priceUsdc:80000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Rwanda — Western Province (Lake Kivu / Nyamasheke)",
    spec:"2–20 hectare hill farms at 1,500–2,000m. Coffee, tea, avocado. Year-round cool climate (equatorial + altitude). Lake access. Very cheap. 2hr from Kigali.",
    buildNote:"Rwanda Africa's governance success story — fastest-rising Ibrahim Index score. Zero nuclear profile. Equatorial highland = no malaria, 2 growing seasons/year. DRC border risk exists — Kivu province awareness required.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:96, disasterRisk:82, populationDensity:72, politicalStability:68 },
    imageSlug:"rea-rwanda-kivu",
    externalUrl:"https://www.lamudi.co.rw/",
  },
  {
    id:"rea-southafrica-karoo", sku:"REA-065",
    name:"Semi-Desert Farm — Great Karoo",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:78,
    tier:"T2", priceUsd:20000000, priceUsdc:200000, highTicket:true, inStock:true, criticalFlag:false,
    location:"South Africa — Northern Cape (Karoo / Graaff-Reinet)",
    spec:"500–20,000 hectare Karoo farms. Borehole water, sheep (Merino + Dorper), solar. Extreme isolation — some farms >100km from a town. Very cheap per hectare.",
    buildNote:"South Africa has crime concerns in cities — the Karoo interior is the opposite. 1 person/km², no nuclear profile, southern hemisphere. Strong title deed system. Rand weakness means USD buyers get extraordinary value.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:92, disasterRisk:80, populationDensity:86, politicalStability:60 },
    imageSlug:"rea-southafrica-karoo",
    externalUrl:"https://www.property24.com/farms-for-sale/",
  },

  // ── OCEANIA ───────────────────────────────────────────────────────────────
  {
    id:"rea-fiji-vanua-levu", sku:"REA-066",
    name:"Tropical Farm — Vanua Levu",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:79,
    tier:"T2", priceUsd:15000000, priceUsdc:150000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Fiji — Vanua Levu (Savusavu district)",
    spec:"2–20 hectare tropical farms with coconut, cacao, pineapple. River and rainwater abundant. 99-year Crown Lease for foreigners. Very remote — 1hr from Savusavu by boat.",
    buildNote:"Fiji southern hemisphere, zero nuclear profile. Vanua Levu: less developed than main island Viti Levu — far cheaper, far more remote. Cyclone risk real (Fiji grade 4–5 cyclones ~every 5 years) — build accordingly.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:98, disasterRisk:66, populationDensity:86, politicalStability:66 },
    imageSlug:"rea-fiji-vanua-levu",
    externalUrl:"https://www.fijipropertyguide.com/",
  },
  {
    id:"rea-vanuatu-espiritu", sku:"REA-067",
    name:"Island Land — Espiritu Santo",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"C", gradeComposite:78,
    tier:"T2", priceUsd:10000000, priceUsdc:100000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Vanuatu — Espiritu Santo (Luganville / Hog Harbour)",
    spec:"2–20 hectare island farms with spring water. Cacao, copra, cattle. 75-year lease. Vanuatu citizenship program via investment (USD 130k) enables passport-free travel to EU.",
    buildNote:"Vanuatu zero nuclear targets. Espiritu Santo: largest island, least dense. Volcanic activity present — choose non-volcanic locations. Citizenship-by-investment gives Vanuatu passport (EU, UK, Russia, HK visa-free). Cyclone risk is real.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:98, disasterRisk:58, populationDensity:90, politicalStability:68 },
    imageSlug:"rea-vanuatu-espiritu",
    externalUrl:"https://www.vanuatuland.com/",
  },

  // ── ADDITIONAL HIGH-VALUE ENTRIES ─────────────────────────────────────────
  {
    id:"rea-austria-burgenland", sku:"REA-068",
    name:"Wine & Farm — Burgenland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:83,
    tier:"T2", priceUsd:22000000, priceUsdc:220000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Austria — Burgenland (Neusiedler See / Südburgenland)",
    spec:"5–50 hectare wine + mixed farms. Lake Neusiedl water, fertile loess soil. EU residency. 1hr from Vienna. Some of Austria's most affordable agricultural land.",
    buildNote:"Austria neutral, EU. Burgenland border area: away from military targets. Hungary border proximity. EU residency, solid property law. Lake Neusiedl is a UNESCO Biosphere Reserve — natural freshwater asset.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:76, disasterRisk:86, populationDensity:84, politicalStability:88 },
    imageSlug:"rea-austria-burgenland",
    externalUrl:"https://www.willhaben.at/iad/immobilien/land-und-forstwirtschaft/burgenland/",
  },
  {
    id:"rea-canada-quebec", sku:"REA-069",
    name:"Forest Farm — Eastern Townships",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:88,
    tier:"T2", priceUsd:22000000, priceUsdc:220000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Canada — Québec (Eastern Townships / Laurentians)",
    spec:"10–200 hectare farms with maple sugar bush, lake access, timber. 4-season growing viable with greenhouse. 1.5hr from Montreal. French-speaking region.",
    buildNote:"Canada GPI top 10. Eastern Townships: dense boreal + farm mix, low nuclear target profile. Montreal is ~200km away (manageable). Strong property rights. Maple syrup income viable. French bilingual required for Quebec citizenship track.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:80, disasterRisk:86, populationDensity:92, politicalStability:92 },
    imageSlug:"rea-canada-quebec",
    externalUrl:"https://www.realtor.ca/map#view=list&Sort=6-D&GeoName=Quebec",
  },
  {
    id:"rea-new-zealand-northland", sku:"REA-070",
    name:"Coastal Farm — Northland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"A", gradeComposite:92,
    tier:"T2", priceUsd:40000000, priceUsdc:400000, highTicket:true, inStock:true, criticalFlag:false,
    location:"New Zealand — Northland (Kaipara / Bay of Islands)",
    spec:"10–100 hectare subtropical coastal farms. Avocado, kiwifruit, cattle. Bore + stream water. 2hr from Auckland. Subtropical growing season extends food security window.",
    buildNote:"NZ GPI #2 globally. Northland: subtropical climate, no nuclear targets (southern hemisphere), very strong property rights. Less remote than South Island but subtropical food production advantage. Cyclone risk minimal vs tropical Pacific.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:99, disasterRisk:88, populationDensity:94, politicalStability:96 },
    imageSlug:"rea-new-zealand-northland",
    externalUrl:"https://www.trademe.co.nz/a/property/residential/sale?search_string=northland&property_type=2",
  },
  {
    id:"rea-australia-queensland", sku:"REA-071",
    name:"Outback Station — Queensland",
    brand:"Tevatha Real Estate", category:"real_estate", grade:"B", gradeComposite:87,
    tier:"T2", priceUsd:35000000, priceUsdc:350000, highTicket:true, inStock:true, criticalFlag:false,
    location:"Australia — Queensland (Darling Downs / Maranoa)",
    spec:"500–50,000 hectare Queensland stations. Dryland grain, cattle, artesian bore water. Very cheap per hectare in inland areas. 3–5hr from Brisbane. Strong foreign investment welcome.",
    buildNote:"Australia GPI top 10. Queensland interior: no nuclear targets, vast distances from cities, strong English common law property rights. Darling Downs: fertile volcanic basalt soil. Drought is a risk — artesian bore water critical.",
    listingNote:"Why this Ark node works",
    priceDisplay:"Varies",
    safetyScore:{ nuclearDistance:94, disasterRisk:78, populationDensity:96, politicalStability:90 },
    imageSlug:"rea-australia-queensland",
    externalUrl:"https://www.realestate.com.au/buy/rural/in-queensland/",
  },
];
